"use client";
import { ArrowRight, Pencil } from "lucide-react";
import Link from "next/link";
import { useMealPlans } from "@/components/coach/MealPlansProvider";
import { foods } from "@/lib/foods";
import { calculateMealTotals, calculatePlanSummary } from "@/lib/meal-plans/calculations";
import { getClientById } from "@/lib/clients";
const foodMap = new Map(foods.map((food) => [food.id, food]));
export default function MenuPreview({ id }: { id: string }) { const { getPlan } = useMealPlans(); const plan = getPlan(id); if (!plan) return <main className="px-4 py-20 text-center"><h1 className="text-3xl font-black">התפריט לא נמצא</h1><Link href="/coach/menus" className="mt-6 inline-block text-[#16A34A]">חזרה לתפריטים</Link></main>; const summary = calculatePlanSummary(plan, foodMap); const client = plan.assignedClientId ? getClientById(plan.assignedClientId) : undefined; return <main className="px-4 pb-20 pt-7 sm:px-6"><div className="mx-auto max-w-3xl"><div className="mb-7 flex flex-wrap items-center justify-between gap-4"><Link href={`/coach/menus/${id}`} className="flex items-center gap-2 text-sm text-[#5B5F5B]"><ArrowRight size={17}/>חזרה לעריכה</Link><Link href={`/coach/menus/${id}`} className="flex items-center gap-2 rounded-2xl border border-[#16A34A]/40 px-4 py-2 text-sm font-bold text-[#16A34A]"><Pencil size={16}/>עריכת התפריט</Link></div><header className="rounded-[30px] border border-[#BBF7D0] bg-[#FFFFFF] p-6 sm:p-8"><p className="text-xs font-bold tracking-widest text-[#16A34A]">התפריט היומי שלי</p><h1 className="mt-3 text-3xl font-black sm:text-4xl">{plan.name}</h1><p className="mt-2 text-sm text-[#5B5F5B]">{client ? `משויך/ת: ${client.fullName}` : "ללא שיוך ללקוח"}</p>{plan.description && <p className="mt-3 leading-7 text-[#5B5F5B]">{plan.description}</p>}<div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["קלוריות", summary.totals.calories], ["חלבון", `${summary.totals.protein} ג׳`], ["פחמימות", `${summary.totals.carbs} ג׳`], ["שומן", `${summary.totals.fat} ג׳`]].map(([label, value]) => <div key={label} className="rounded-2xl bg-[#F7F8F7] p-4 text-center"><strong className="text-xl">{value}</strong><span className="mt-1 block text-xs text-[#5B5F5B]">{label}</span></div>)}</div></header><div className="mt-5 space-y-4">{[...plan.meals].sort((a,b) => a.order-b.order).map((meal) => { const totals = calculateMealTotals(meal, foodMap); return <section key={meal.id} className="rounded-[24px] border border-[#E5E7E5] bg-[#FFFFFF] p-5"><h2 className="text-xl font-black">{meal.name}</h2>{meal.note && <p className="mt-1 text-sm text-[#5B5F5B]">{meal.note}</p>}<ul className="mt-4 divide-y divide-[#E5E7E5]">{meal.items.map((item) => { const food = foodMap.get(item.foodId); return food && <li key={item.id} className="flex items-center justify-between gap-4 py-3"><span>{food.name}</span><strong className="text-sm text-[#16A34A]">{item.quantityGrams} גרם</strong></li>; })}</ul><p className="mt-3 border-t border-[#E5E7E5] pt-3 text-sm text-[#5B5F5B]">{totals.calories} קל׳ · חלבון {totals.protein} · פחמימות {totals.carbs} · שומן {totals.fat}</p></section>; })}</div></div></main>; }
