"use client";
import { Copy, Eye, Pencil, Trash2 } from "lucide-react";
import Link from "next/link";
import { clients } from "@/lib/clients";
import { foods } from "@/lib/foods";
import { calculatePlanSummary } from "@/lib/meal-plans/calculations";
import type { MealPlan } from "@/lib/meal-plans/types";
const foodMap = new Map(foods.map((food) => [food.id, food]));
export default function MenuCard({ plan, onDuplicate, onDelete }: { plan: MealPlan; onDuplicate: () => void; onDelete: () => void }) { const summary = calculatePlanSummary(plan, foodMap); const client = clients.find((item) => item.id === plan.assignedClientId); return <article className="rounded-[26px] border border-[#E5E7E5] bg-[#FFFFFF] p-5"><div className="flex items-start justify-between gap-4"><div><span className={`rounded-full border px-2.5 py-1 text-[11px] font-bold ${plan.status === "active" ? "border-[#16A34A]/30 bg-[#ECFDF3] text-[#16A34A]" : "border-[#E5E7E5] bg-[#F7F8F7] text-[#0B0B0B]"}`}>{plan.status === "active" ? "פעיל" : "טיוטה"}</span><h2 className="mt-3 text-xl font-black">{plan.name}</h2><p className="mt-1 text-sm text-[#5B5F5B]">{client ? `משויך/ת: ${client.fullName}` : "לא משויך ללקוח"}</p></div><div className="flex"><button type="button" aria-label={`שכפול ${plan.name}`} onClick={onDuplicate} className="rounded-xl p-2 text-[#16A34A]"><Copy size={18}/></button><button type="button" aria-label={`מחיקת ${plan.name}`} onClick={onDelete} className="rounded-xl p-2 text-[#DC2626]"><Trash2 size={18}/></button></div></div><div className="my-5 grid grid-cols-3 gap-2 text-center"><Metric value={summary.totals.calories} label="קלוריות"/><Metric value={`${summary.totals.protein} ג׳`} label="חלבון"/><Metric value={summary.mealCount} label="ארוחות"/></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-[#E5E7E5] pt-4"><span className="text-xs text-[#3F433F]">עודכן {new Intl.DateTimeFormat("he-IL",{timeZone:"Asia/Jerusalem"}).format(new Date(`${plan.updatedAt}T12:00:00`))}</span><div className="flex gap-3"><Link href={`/coach/menus/${plan.id}/preview`} className="flex items-center gap-1 text-sm text-[#3F433F]"><Eye size={15}/>תצוגה</Link><Link href={`/coach/menus/${plan.id}`} className="flex items-center gap-1 text-sm font-bold text-[#16A34A]">עריכה <Pencil size={15}/></Link></div></div></article>; }
function Metric({ value, label }: { value: string | number; label: string }) { return <div className="rounded-2xl bg-[#F7F8F7] p-3"><strong className="block">{value}</strong><span className="text-[11px] text-[#5B5F5B]">{label}</span></div>; }
