"use server";
import { revalidatePath } from "next/cache";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getAuthContext } from "@/lib/data/product-repository";
export type FreeMenuState = Readonly<{ ok: boolean; message?: string }>;
const num=(v:FormDataEntryValue|null)=>{const n=Number(String(v??"").trim());return Number.isFinite(n)&&n>=0?n:null};
export async function enableFreeMenu(_:FreeMenuState,form:FormData):Promise<FreeMenuState>{const a=await getAuthContext();if(!a||a.role!=="coach")return{ok:false,message:"אין הרשאה."};const date=String(form.get("date")??"");const clientId=String(form.get("clientId")??"");if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!clientId)return{ok:false,message:"יש לבחור לקוח ותאריך תקינים."};const s=await createSupabaseServerClient();const{error}=await s.rpc("enable_free_menu_day",{p_client_id:clientId,p_date:date,p_calorie_target:num(form.get("calorieTarget")),p_protein_target:num(form.get("proteinTarget"))});if(error)return{ok:false,message:"לא ניתן להפעיל תפריט חופשי."};revalidatePath(`/coach/clients/${clientId}`);return{ok:true,message:"התפריט החופשי הופעל."}}
export async function saveFreeMenuEntry(_:FreeMenuState,form:FormData):Promise<FreeMenuState>{const a=await getAuthContext();if(!a||a.role!=="client")return{ok:false,message:"אין הרשאה."};const date=String(form.get("date")??"");const name=String(form.get("name")??"").trim();const quantity=num(form.get("quantity"));if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!name||quantity===null||quantity<=0)return{ok:false,message:"יש למלא שם וכמות חיובית."};const s=await createSupabaseServerClient();const{error}=await s.rpc("save_free_menu_entry_v2",{p_date:date,p_food_id:String(form.get("foodId")??""),p_name:name,p_quantity:quantity,p_unit:String(form.get("unit")??"g"),p_meal_label:String(form.get("meal")??"חופשי"),p_eaten_at:new Date(`${date}T${String(form.get("time")??"12:00")}:00`).toISOString(),p_notes:String(form.get("notes")??""),p_calories:num(form.get("calories")),p_protein:num(form.get("protein")),p_carbohydrates:num(form.get("carbs")),p_fat:num(form.get("fat")),p_request_key:String(form.get("requestKey")??"")});if(error)return{ok:false,message:"הפריט לא נשמר. ודאו שהיום החופשי פעיל."};revalidatePath("/nutrition");return{ok:true,message:"הפריט נשמר."}}
export async function deleteFreeMenuEntry(form:FormData){const a=await getAuthContext();if(!a||a.role!=="client")return;const s=await createSupabaseServerClient();await s.rpc("delete_free_menu_entry",{p_entry_id:String(form.get("id")??"")});revalidatePath("/nutrition")}
