/* eslint-disable @next/next/no-img-element -- profile URLs are coach-provided and may use arbitrary approved storage hosts. */
import { notFound, redirect } from "next/navigation";
import SubmitButton from "@/components/forms/SubmitButton";
import ReviewCheckInForm from "@/components/coach/ReviewCheckInForm";
import { resetClientDevice } from "@/app/actions/product";
import { getAuthContext, getCoachClientDashboard } from "@/lib/data/product-repository";
import EnableFreeMenu from "@/components/coach/EnableFreeMenu";
import { resendClientInvite, sendClientMagicLink, sendClientPasswordReset } from "@/app/actions/onboarding";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { formatIsraelDateTime } from "@/lib/date-time";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import ClientDetailExtras from "@/components/coach/ClientDetailExtras";

const date = (value: string | null) => value ? formatIsraelDateTime(value) : "אין נתון";
const number = (value: number) => Math.round(value).toLocaleString("he-IL");

export default async function CoachClientPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ created?: string; invite?: string; login?: string }> }) {
  const auth = await getAuthContext(); if (!auth) redirect("/login"); if (auth.role !== "coach") redirect("/unauthorized");
  const { id } = await params; const query=await searchParams; const data = await getCoachClientDashboard(auth.id, id); if (!data) notFound();
  const lastCheckIn = data.checkIns[0] ?? null;
  const latestNavelMeasurement=data.progress.find((entry)=>entry.navel_circumference!==null);
  const alertRows = [!lastCheckIn ? "צ׳ק־אין ממתין" : null, data.workouts.assignment && data.workouts.weeklyCompletionPercent < 100 ? "אימון שבועי שטרם הושלם" : null, data.menu && data.nutrition.completionPercent < 100 ? "ארוחות שטרם סומנו" : null].filter(Boolean);
  const intake=data.profile.clientProfile;
  const supabase=await createSupabaseServerClient();
  const [{ data: invitations }, { data: contentRows }, { data: contentAssignments }, { data: clientNotifications }, { data: coachNotes }]=await Promise.all([
    supabase.from("client_invitation_statuses").select("id,status,effective_status,sent_at,expires_at,opened_at,onboarding_completed_at").eq("client_id",id).order("sent_at",{ascending:false}),
    supabase.from("content_items").select("id,title").eq("status","published").order("sort_order"),
    supabase.from("client_content_assignments").select("content_item_id").eq("client_id",id),
    supabase.from("notifications").select("id,title,body,href,created_at,read_at").eq("recipient_id",id).order("created_at",{ascending:false}).limit(20),
    supabase.from("coach_client_notes").select("id,body,created_at,updated_at").eq("client_id",id).eq("coach_id",auth.id).order("created_at",{ascending:false}),
  ]);
  const { data: { user: authUser } } = await createSupabaseAdminClient().auth.admin.getUserById(id);
  const accountActivated=Boolean(authUser?.email_confirmed_at);
  const latestInvitation=invitations?.[0] ?? null;
  const invitationExpired=latestInvitation?.effective_status==="expired";
  const invitationStatus=intake?.onboarding_completed ? "לקוח פעיל" : !latestInvitation ? "טרם נשלחה הזמנה" : invitationExpired ? "ההזמנה פגה" : latestInvitation.effective_status==="opened" ? "ההזמנה נפתחה" : "הזמנה נשלחה";
  const preferences=intake?.preferences && typeof intake.preferences==="object" && !Array.isArray(intake.preferences) ? Object.entries(intake.preferences).filter(([, item]) => item !== null && item !== "") : [];
  return <main className="px-4 py-8 sm:px-6"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex items-center gap-4">{data.profile.avatar_url ? <img src={data.profile.avatar_url} alt="" className="size-16 rounded-3xl object-cover"/> : <span className="grid size-16 place-items-center rounded-3xl bg-[#D4AF37]/10 text-2xl font-black text-[#E7C85D]">{data.profile.full_name.slice(0, 1)}</span>}<div><p className="text-xs text-[#D4AF37]">לקוח משויך</p><h1 className="mt-1 text-3xl font-black">{data.profile.full_name}</h1><p className="mt-1 text-sm text-zinc-500">{data.profile.email} · כניסה אחרונה: {date(data.lastLoginAt)}</p></div></div><form action={resetClientDevice}><input type="hidden" name="clientId" value={id}/><SubmitButton idle="איפוס מכשיר" pending="מאפסים…" className="min-h-12 rounded-2xl border border-red-400/30 px-5 font-bold text-red-300 disabled:opacity-50"/></form></div>
    {(query.created==="1" || query.invite==="resent" || query.login) && <p role="status" className="mt-5 rounded-2xl border border-emerald-400/30 bg-emerald-400/10 p-4 text-sm text-emerald-100">{query.invite==="resent" ? "נשלחה הזמנה חדשה ללקוח." : query.login==="access-link-sent" ? "נשלח קישור כניסה מאובטח ללקוח." : query.login==="password-reset-sent" ? "קישור לאיפוס סיסמה נשלח ללקוח." : "הלקוח נוצר והוזמן להשלמת הקליטה."}</p>}
    <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Card label="יעד" value={data.profile.clientProfile?.goal ?? "לא הוגדר"}/><Card label="משקל אחרון" value={data.progress[0] ? `${data.progress[0].weight} ק״ג` : "אין מדידה"}/><Card label="צ׳ק־אין אחרון" value={lastCheckIn ? date(lastCheckIn.submitted_at) : "ממתין"}/><Card label="היקף טבור" value={latestNavelMeasurement ? `${latestNavelMeasurement.navel_circumference} ס״מ` : "אין עדיין מדידת היקף טבור"}/></section>
    <section className="mt-6"><Panel title="סטטוס הזמנה" description={invitationStatus}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="נשלחה לאחרונה" value={latestInvitation ? date(latestInvitation.sent_at) : "טרם נשלחה"}/><Metric label="בתוקף עד" value={latestInvitation && !invitationExpired ? date(latestInvitation.expires_at) : "לא בתוקף"}/><Metric label="נפתחה" value={latestInvitation?.opened_at ? date(latestInvitation.opened_at) : "טרם נפתחה"}/><Metric label="Onboarding" value={intake?.onboarding_completed_at ? date(intake.onboarding_completed_at) : "ממתין"}/></div><p className="mt-4 text-sm text-zinc-400">סה״כ הזמנות שנשלחו: {invitations?.length ?? 0}</p><div className="mt-4 flex flex-wrap gap-2">{intake?.onboarding_completed ? <><form action={sendClientMagicLink}><input type="hidden" name="clientId" value={id}/><SubmitButton idle="שליחת Magic Link" pending="שולחים…" className="min-h-12 rounded-2xl border border-[#D4AF37]/40 px-5 font-bold text-[#E7C85D] disabled:opacity-50"/></form><form action={sendClientPasswordReset}><input type="hidden" name="clientId" value={id}/><SubmitButton idle="איפוס סיסמה" pending="שולחים…" className="min-h-12 rounded-2xl border border-[#D4AF37]/40 px-5 font-bold text-[#E7C85D] disabled:opacity-50"/></form></> : accountActivated ? <form action={sendClientMagicLink}><input type="hidden" name="clientId" value={id}/><SubmitButton idle="שלח קישור כניסה להשלמת הקליטה" pending="שולחים…" className="min-h-12 rounded-2xl border border-[#D4AF37]/40 px-5 font-bold text-[#E7C85D] disabled:opacity-50"/></form> : <form action={resendClientInvite}><input type="hidden" name="clientId" value={id}/><SubmitButton idle="שלח הזמנה מחדש" pending="שולחים…" className="min-h-12 rounded-2xl border border-[#D4AF37]/40 px-5 font-bold text-[#E7C85D] disabled:opacity-50"/></form>}</div>{accountActivated&&!intake?.onboarding_completed&&<p className="mt-3 text-sm text-zinc-400">החשבון כבר אומת. נשלח ללקוח קישור כניסה מאובטח להמשך הקליטה, במקום הזמנה נוספת.</p>}</Panel></section>
    <section className="mt-6"><Panel title="נתוני קליטה" description={intake?.onboarding_completed ? `הקליטה הושלמה ב-${date(intake.onboarding_completed_at ?? null)}` : "ממתין להשלמת קליטה מצד הלקוח"}>{intake ? <div className="grid gap-3 sm:grid-cols-2"><Metric label="רמת פעילות" value={intake.activity_level ?? "לא הוגדר"}/><Metric label="יעד משקל" value={intake.target_weight ? `${intake.target_weight} ק״ג` : "לא הוגדר"}/>{preferences.map(([key,item])=><Metric key={key} label={key.replaceAll("_"," ")} value={Array.isArray(item) ? item.join(", ") : String(item)}/>)}</div> : <Empty text="אין נתוני קליטה זמינים."/>}</Panel></section>
    {alertRows.length > 0 && <section className="mt-5 rounded-[22px] border border-amber-400/25 bg-amber-400/[.06] p-4"><h2 className="font-black text-amber-200">דורש תשומת לב</h2><ul className="mt-2 list-inside list-disc text-sm text-amber-100">{alertRows.map((alert) => <li key={alert}>{alert}</li>)}</ul></section>}
    <section className="mt-6 grid gap-5 lg:grid-cols-2"><Panel title="תזונה" description={data.menu ? data.menu.title : "אין תפריט פעיל"}>{data.menu ? <><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="השלמת היום" value={`${data.nutrition.completionPercent}%`}/><Metric label="קלוריות" value={number(data.nutrition.totals.calories)}/><Metric label="חלבון" value={`${number(data.nutrition.totals.protein)} ג׳`}/><Metric label="פחמימות / שומן" value={`${number(data.nutrition.totals.carbs)} / ${number(data.nutrition.totals.fat)} ג׳`}/></div><p className="mt-4 text-sm text-zinc-400">{data.nutrition.completedItems} מתוך {data.nutrition.plannedItems} פריטים סומנו היום.</p></> : <Empty text="ללקוח עדיין לא שויך תפריט פעיל."/>}</Panel><Panel title="אימונים" description={data.workouts.program?.name ?? "אין תוכנית פעילה"}>{data.workouts.assignment ? <div className="grid grid-cols-2 gap-3"><Metric label="השלמת השבוע" value={`${data.workouts.weeklyCompletionPercent}%`}/><Metric label="אימון אחרון" value={date(data.workouts.lastCompletedAt)}/><Metric label="אימון הבא" value={data.workouts.nextDayName ?? "לא הוגדר"}/><Metric label="תדירות" value={`${data.workouts.assignment.weekly_frequency} בשבוע`}/></div> : <Empty text="ללקוח עדיין לא שויכה תוכנית אימונים."/>}</Panel></section>
    <section className="mt-6 grid gap-5 lg:grid-cols-2"><Panel title="התקדמות" description="משקל והיקף טבור"><div className="space-y-2">{data.progress.slice(0, 6).map((entry) => <p key={entry.id} className="rounded-xl bg-black/20 p-3 text-sm">{entry.date} · {entry.weight} ק״ג · היקף טבור {entry.navel_circumference ?? "—"}</p>)}</div>{!data.progress.length && <Empty text="אין מדידות שמורות."/>}</Panel><Panel title="צ׳ק־אין" description="עדכון אחרון, הערות ותגובה"><div className="space-y-3">{data.checkIns.slice(0, 4).map((entry) => <article key={entry.id} className="rounded-xl bg-black/20 p-4"><p className="text-sm text-zinc-400">{date(entry.submitted_at)} · היצמדות {entry.adherence}/5 · אנרגיה {entry.energy}/5 · שינה {entry.sleep}/5</p>{entry.notes && <p className="mt-2 text-sm">{entry.notes}</p>}{entry.coach_response ? <p className="mt-3 border-r-2 border-[#D4AF37] pr-3 text-sm text-[#E7C85D]">{entry.coach_response}</p> : <ReviewCheckInForm checkInId={entry.id} clientId={id}/>}<p className="mt-3 text-xs text-zinc-600">תמונות: אין תמונות זמינות בצ׳ק־אין זה.</p></article>)}</div>{!data.checkIns.length && <Empty text="אין צ׳ק־אין שמור."/>}</Panel></section>
    <EnableFreeMenu clientId={id}/>
    <ClientDetailExtras clientId={id} content={(contentRows??[]).map((item)=>({...item,assigned:(contentAssignments??[]).some((assignment)=>assignment.content_item_id===item.id)}))} notifications={clientNotifications??[]} notes={coachNotes??[]}/>
  </div></main>;
}
function Card({ label, value }: { label: string; value: string }) { return <div className="rounded-[22px] border border-[#292929] bg-[#151515] p-4"><p className="text-xs text-zinc-500">{label}</p><strong className="mt-2 block">{value}</strong></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-black/20 p-3"><p className="text-xs text-zinc-500">{label}</p><strong className="mt-1 block text-sm">{value}</strong></div>; }
function Panel({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <section className="rounded-[24px] border border-[#292929] bg-[#151515] p-5"><h2 className="text-xl font-black">{title}</h2><p className="mt-1 text-sm text-zinc-500">{description}</p><div className="mt-4">{children}</div></section>; }
function Empty({ text }: { text: string }) { return <p className="rounded-xl border border-dashed border-[#333] p-5 text-center text-sm text-zinc-500">{text}</p>; }
