"use client";
import Link from "next/link";
import { CalendarCheck, ChevronLeft, ClipboardCheck, LineChart, Salad, Scale, Target } from "lucide-react";
import ClientMealCard from "./ClientMealCard";
import MacroProgress from "./MacroProgress";
import { useClientApp } from "./ClientAppProvider";
import { currentClient, currentLatestCheckIn, currentPlan, currentPlanSummary, currentProgress, getMealTotals } from "@/lib/client-app";
import { addMacros, ZERO_MACROS } from "@/lib/meal-plans/calculations";
export default function ClientDashboard() { const { mealStatuses } = useClientApp(); const consumed = currentPlan ? addMacros(...currentPlan.meals.filter((meal) => mealStatuses[meal.id] === "eaten").map(getMealTotals)) : ZERO_MACROS; const todayMeals = currentPlan?.meals.slice(0, 2) ?? []; return <><header className="mb-7"><p className="text-xs font-bold tracking-[.18em] text-[#16A34A]">START</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">שלום, {currentClient.fullName.split(" ")[0]}</h1><p className="mt-2 text-sm text-[#5B5F5B]">הנה תמונת המצב שלך להיום.</p></header><section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric icon={<Scale/>} label="משקל נוכחי" value={`${currentProgress.latestWeight ?? currentClient.currentWeight} ק״ג`}/><Metric icon={<Target/>} label="משקל יעד" value={`${currentClient.targetWeight} ק״ג`}/><Metric icon={<LineChart/>} label="שינוי מתחילת המעקב" value={`${currentProgress.weightChangeFromStart ?? 0} ק״ג`}/><Metric icon={<CalendarCheck/>} label="צ׳ק-אין אחרון" value={currentLatestCheckIn?.date ?? "אין עדכון"}/></section><section className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-[26px] border border-[#BBF7D0] bg-gradient-to-br from-[#FFFFFF] to-[#111] p-5"><h2 className="text-xl font-black">התקדמות תזונתית היום</h2><div className="mt-5 space-y-5"><MacroProgress label="קלוריות" current={consumed.calories} target={currentPlan?.targets.calories}/><MacroProgress label="חלבון" current={consumed.protein} target={currentPlan?.targets.protein} unit="ג׳"/></div><p className="mt-4 text-xs text-[#3F433F]">סך התפריט: {currentPlanSummary?.totals.calories ?? 0} קל׳ · {currentPlanSummary?.totals.protein ?? 0} ג׳ חלבון</p></div><div className="rounded-[26px] border border-[#E5E7E5] bg-[#FFFFFF] p-5"><h2 className="text-xl font-black">פעולות מהירות</h2><div className="mt-4 grid grid-cols-2 gap-3"><Quick href="/nutrition" icon={<Salad/>} label="הארוחות שלי"/><Quick href="/check-in" icon={<ClipboardCheck/>} label="צ׳ק-אין שבועי"/><Quick href="/progress" icon={<LineChart/>} label="התקדמות"/><Quick href="/profile" icon={<Target/>} label="היעדים שלי"/></div></div></section><section className="mt-6"><div className="mb-4 flex items-center justify-between"><h2 className="text-2xl font-black">הארוחות של היום</h2><Link href="/nutrition" className="flex items-center gap-1 text-sm font-bold text-[#16A34A]">לכל הארוחות <ChevronLeft size={16}/></Link></div>{todayMeals.length ? <div className="grid gap-4 md:grid-cols-2">{todayMeals.map((meal) => <ClientMealCard key={meal.id} meal={meal} compact/>)}</div> : <p className="rounded-[24px] border border-dashed border-[#E5E7E5] p-10 text-center text-[#5B5F5B]">עדיין אין תפריט משויך.</p>}</section></>; }
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="rounded-[22px] border border-[#E5E7E5] bg-[#FFFFFF] p-4"><span className="text-[#16A34A] [&>svg]:size-5">{icon}</span><span className="mt-3 block text-xs text-[#5B5F5B]">{label}</span><strong className="mt-1 block text-lg sm:text-xl">{value}</strong></div>; }
function Quick({ href, icon, label }: { href: string; icon: React.ReactNode; label: string }) { return <Link href={href} className="flex min-h-20 flex-col justify-center gap-2 rounded-2xl border border-[#E5E7E5] bg-[#F7F8F7] p-3 text-sm font-bold hover:border-[#16A34A]/60 hover:text-[#16A34A]"><span className="text-[#16A34A] [&>svg]:size-5">{icon}</span>{label}</Link>; }
