"use client";
import { useActionState } from "react";
import { saveCheckIn, type SaveState } from "@/app/actions/product";
import SubmitButton from "@/components/forms/SubmitButton";
import CheckInPhotoInputs from "@/components/client/CheckInPhotoInputs";
const initial: SaveState = { ok: false };
const ratings = [{ name:"adherence",label:"התמדה השבוע" },{ name:"hunger",label:"רעב" },{ name:"energy",label:"אנרגיה" },{ name:"sleep",label:"איכות שינה" },{ name:"mood",label:"מצב רוח" }];
export default function PersistedCheckInForm({photosRequired=false}:{photosRequired?:boolean}){const[state,action]=useActionState(saveCheckIn,initial);return <form action={action} className="space-y-4"><section className="grid gap-3 rounded-[22px] border border-[#292929] bg-[#151515] p-5 sm:grid-cols-2"><Field name="weight" label="משקל (ק״ג)" required/><Field name="navelCircumference" label="היקף טבור (ס״מ)" required/><Field name="workoutsCompleted" label="כמה אימונים בוצעו" integer/><Field name="mealPlanDays" label="כמה ימים עמדת בתפריט" integer max="7"/></section><CheckInPhotoInputs required={photosRequired}/>{ratings.map(item=><fieldset key={item.name} className="rounded-[22px] border border-[#292929] bg-[#151515] p-5"><legend className="px-1 font-black">{item.label}</legend><div className="mt-3 grid grid-cols-5 gap-2" dir="ltr">{[1,2,3,4,5,6,7,8,9,10].map(value=><label key={value} className="grid min-h-11 place-items-center rounded-xl border border-[#333] has-[:checked]:border-[#D4AF37] has-[:checked]:bg-[#D4AF37] has-[:checked]:text-black"><input className="sr-only" type="radio" name={item.name} value={value} required/><span className="font-black">{value}</span></label>)}</div></fieldset>)}<label className="block rounded-[22px] border border-[#292929] bg-[#151515] p-5 font-bold">הערות<textarea name="notes" className="nutrition-input mt-3 min-h-28"/></label><div className="flex items-center gap-3"><SubmitButton idle="שליחת צ׳ק־אין" pending="שולחים…"/>{state.message&&<p role={state.ok?"status":"alert"} className={state.ok?"text-sm text-emerald-400":"text-sm text-red-400"}>{state.message}</p>}</div></form>}
function Field({name,label,integer=false,max,required=false}:{name:string;label:string;integer?:boolean;max?:string;required?:boolean}){return <label className="text-sm font-bold">{label}<input className="nutrition-input mt-2" name={name} type="number" min="0.1" max={max} step={integer?"1":"0.1"} required={required}/></label>}
