"use client";

import { ChevronDown, ChevronUp, Plus, Save, Search, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { useWorkouts } from "@/components/workouts/WorkoutProvider";
import type { WorkoutDay, WorkoutExercise, WorkoutProgram, WorkoutSetPrescription } from "@/lib/workouts/types";

const uid=(prefix:string)=>`${prefix}-${crypto.randomUUID()}`;
const emptyDay=(order:number):WorkoutDay=>({id:uid("workout-day"),name:`אימון ${order+1}`,order,exercises:[]});
const normalizeDays=(days:readonly WorkoutDay[])=>days.map((day,index)=>({...day,order:index,exercises:day.exercises.map((exercise,exerciseIndex)=>({...exercise,order:exerciseIndex,setPrescriptions:exercise.setPrescriptions?.map((set,setIndex)=>({...set,order:setIndex}))}))}));

export function NewProgramEditor(){
  const{saveProgram}=useWorkouts(); const router=useRouter();
  const[draft,setDraft]=useState<WorkoutProgram>({id:uid("coach-program"),name:"",description:"",programType:"",difficulty:"",trainingFrequency:3,equipment:[],sourceWorkbook:"נבנה על ידי המאמן",status:"active",official:false,days:[emptyDay(0)]});
  const[saving,setSaving]=useState(false); const[message,setMessage]=useState("");
  return <ProgramEditor draft={draft} setDraft={setDraft} onSave={async()=>{setSaving(true);setMessage("");const ok=await saveProgram({...draft,name:draft.name.trim(),days:normalizeDays(draft.days)});setSaving(false);if(ok){setMessage("התוכנית נוצרה ונשמרה ב-Supabase.");router.replace("/coach/workouts");router.refresh()}else setMessage("שמירת התוכנית נכשלה.")}} saving={saving} message={message}/>;
}

export default function CustomProgramEditor({id}:{id:string}){
  const{getProgram,saveProgram}=useWorkouts(); const existing=getProgram(id); const[draft,setDraft]=useState<WorkoutProgram|undefined>(existing); const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");
  if(!draft||draft.official)return null;
  return <ProgramEditor draft={draft} setDraft={setDraft} onSave={async()=>{setSaving(true);setMessage("");const ok=await saveProgram({...draft,name:draft.name.trim(),days:normalizeDays(draft.days)});setSaving(false);setMessage(ok?"השינויים נשמרו ב-Supabase.":"שמירת התוכנית נכשלה.")}} saving={saving} message={message}/>;
}

function ProgramEditor({draft,setDraft,onSave,saving,message}:{draft:WorkoutProgram;setDraft:(program:WorkoutProgram)=>void;onSave:()=>Promise<void>;saving:boolean;message:string}){
 const{snapshot}=useWorkouts();const[query,setQuery]=useState(""); const choices=useMemo(()=>snapshot.exercises.filter((exercise)=>exercise.status==="active"&&(`${exercise.name} ${exercise.category??""} ${exercise.primaryMuscleGroup??""}`).toLocaleLowerCase("he").includes(query.trim().toLocaleLowerCase("he"))).slice(0,30),[query,snapshot.exercises]);
 const patch=(value:Partial<WorkoutProgram>)=>setDraft({...draft,...value});
 const setDays=(days:WorkoutDay[])=>patch({days:normalizeDays(days)});
 const addDay=()=>setDays([...draft.days,emptyDay(draft.days.length)]);
 const moveDay=(index:number,direction:-1|1)=>{const target=index+direction;if(target<0||target>=draft.days.length)return;const next=[...draft.days];[next[index],next[target]]=[next[target],next[index]];setDays(next)};
 const patchDay=(dayId:string,value:Partial<WorkoutDay>)=>setDays(draft.days.map(day=>day.id===dayId?{...day,...value}:day));
 const addExercise=(dayId:string,exerciseId:string)=>setDays(draft.days.map(day=>day.id===dayId?{...day,exercises:[...day.exercises,{id:uid("workout-exercise"),exerciseId,order:day.exercises.length,sets:"3",reps:"8-12",rest:"90 שניות",notes:"",setPrescriptions:prescriptions("3","8-12")}]}:day));
 const patchExercise=(dayId:string,exerciseId:string,value:Partial<WorkoutExercise>)=>setDays(draft.days.map(day=>day.id===dayId?{...day,exercises:day.exercises.map(exercise=>exercise.id===exerciseId?{...exercise,...value}:exercise)}:day));
 const moveExercise=(dayId:string,index:number,direction:-1|1)=>{setDays(draft.days.map(day=>{if(day.id!==dayId)return day;const target=index+direction;if(target<0||target>=day.exercises.length)return day;const next=[...day.exercises];[next[index],next[target]]=[next[target],next[index]];return{...day,exercises:next}}))};
 const changeSets=(dayId:string,exercise:WorkoutExercise,sets:string)=>{const count=Math.max(0,Math.min(12,Number.parseInt(sets,10)||0));patchExercise(dayId,exercise.id,{sets:sets||undefined,setPrescriptions:count?prescriptions(String(count),exercise.reps??""):[]})};
 return <main className="px-4 pb-20 pt-7 sm:px-6"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-black tracking-widest text-[#16A34A]">תוכנית אימונים</p><h1 className="mt-2 text-3xl font-black">{draft.name||"תוכנית חדשה"}</h1></div><button type="button" disabled={saving||!draft.name.trim()||!draft.days.length} onClick={onSave} className="inline-flex min-h-12 items-center gap-2 rounded-2xl bg-[#16A34A] px-5 font-black text-[#FFFFFF] disabled:opacity-50"><Save size={18}/>{saving?"שומרים…":"שמירת תוכנית"}</button></div>{message&&<p role="status" className="mt-4 rounded-xl border border-[#E5E7E5] p-3 text-sm">{message}</p>}
 <section className="mt-6 grid gap-3 rounded-[24px] border border-[#E5E7E5] bg-[#FFFFFF] p-5 sm:grid-cols-2"><Input label="שם התוכנית" value={draft.name} onChange={name=>patch({name})}/><Input label="תיאור" value={draft.description??""} onChange={description=>patch({description})}/><Input label="סוג" value={draft.programType??""} onChange={programType=>patch({programType})}/><Input label="רמה" value={draft.difficulty??""} onChange={difficulty=>patch({difficulty})}/><Input label="תדירות שבועית" type="number" value={String(draft.trainingFrequency??"")} onChange={value=>patch({trainingFrequency:value?Math.min(7,Math.max(1,Number(value))):undefined})}/><Input label="ציוד (מופרד בפסיקים)" value={draft.equipment.join(", ")} onChange={value=>patch({equipment:value.split(",").map(item=>item.trim()).filter(Boolean)})}/></section>
 <section className="mt-6 rounded-[24px] border border-[#E5E7E5] bg-[#FFFFFF] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">מאגר תרגילים</h2><p className="mt-1 text-sm text-[#5B5F5B]">חיפוש, בחירה והוספה ליום אימון.</p></div><label className="relative min-w-60"><Search className="absolute right-3 top-3 text-[#16A34A]" size={17}/><input className="nutrition-input pr-9" value={query} onChange={event=>setQuery(event.target.value)} placeholder="חיפוש תרגיל או קבוצת שריר"/></label></div><div className="mt-4 grid max-h-64 gap-2 overflow-y-auto md:grid-cols-2">{choices.map(exercise=><div key={exercise.id} className="flex items-center justify-between gap-3 rounded-xl bg-[#F7F8F7] p-3"><span className="text-sm"><strong>{exercise.name}</strong><small className="mt-1 block text-[#5B5F5B]">{exercise.primaryMuscleGroup??exercise.category??"ללא סיווג"}</small></span><select aria-label={`הוספת ${exercise.name} ליום`} className="rounded-lg border border-[#E5E7E5] bg-[#FFFFFF] p-2 text-xs" defaultValue="" onChange={event=>{if(event.target.value){addExercise(event.target.value,exercise.id);event.currentTarget.value=""}}}><option value="">הוספה ליום…</option>{draft.days.map(day=><option key={day.id} value={day.id}>{day.name}</option>)}</select></div>)}</div></section>
 <div className="mt-6 space-y-4">{draft.days.map((day,dayIndex)=><section key={day.id} className="rounded-[24px] border border-[#E5E7E5] bg-[#FFFFFF] p-5"><div className="flex flex-wrap items-center gap-2"><input aria-label="שם יום אימון" className="nutrition-input max-w-sm font-black" value={day.name} onChange={event=>patchDay(day.id,{name:event.target.value})}/><button aria-label="הזזת יום למעלה" className="icon-button" disabled={dayIndex===0} onClick={()=>moveDay(dayIndex,-1)}><ChevronUp size={18}/></button><button aria-label="הזזת יום למטה" className="icon-button" disabled={dayIndex===draft.days.length-1} onClick={()=>moveDay(dayIndex,1)}><ChevronDown size={18}/></button><button aria-label="מחיקת יום אימון" className="icon-button text-[#DC2626]" disabled={draft.days.length===1} onClick={()=>setDays(draft.days.filter(item=>item.id!==day.id))}><Trash2 size={18}/></button><span className="mr-auto text-sm text-[#5B5F5B]">{day.exercises.length} תרגילים</span></div><div className="mt-4 space-y-3">{day.exercises.map((entry,index)=>{const exercise=snapshot.exercises.find(item=>item.id===entry.exerciseId);return <article key={entry.id} className="rounded-2xl border border-[#E5E7E5] bg-[#F7F8F7] p-4"><div className="flex flex-wrap items-center gap-2"><strong>{exercise?.name??"תרגיל"}</strong><span className="text-xs text-[#5B5F5B]">{exercise?.primaryMuscleGroup??exercise?.category??""}</span><button aria-label="הזזת תרגיל למעלה" className="icon-button mr-auto" disabled={index===0} onClick={()=>moveExercise(day.id,index,-1)}><ChevronUp size={16}/></button><button aria-label="הזזת תרגיל למטה" className="icon-button" disabled={index===day.exercises.length-1} onClick={()=>moveExercise(day.id,index,1)}><ChevronDown size={16}/></button><button aria-label="מחיקת תרגיל" className="icon-button text-[#DC2626]" onClick={()=>setDays(draft.days.map(item=>item.id===day.id?{...item,exercises:item.exercises.filter(value=>value.id!==entry.id)}:item))}><Trash2 size={16}/></button></div><div className="mt-3 grid gap-2 sm:grid-cols-4"><Input label="סטים" type="number" value={entry.sets??""} onChange={sets=>changeSets(day.id,entry,sets)}/><Input label="טווח חזרות" value={entry.reps??""} onChange={reps=>patchExercise(day.id,entry.id,{reps,setPrescriptions:prescriptions(entry.sets??"",reps)})}/><Input label="מנוחה" value={entry.rest??""} onChange={rest=>patchExercise(day.id,entry.id,{rest})}/><Input label="טכניקה / הערה" value={entry.notes??""} onChange={notes=>patchExercise(day.id,entry.id,{notes})}/></div></article>})}{!day.exercises.length&&<p className="rounded-xl border border-dashed border-[#E5E7E5] p-4 text-sm text-[#5B5F5B]">חפשו תרגיל במאגר ובחרו את היום הזה.</p>}</div></section>)}</div><button type="button" onClick={addDay} className="mt-5 inline-flex min-h-12 items-center gap-2 rounded-2xl border border-[#16A34A]/40 px-5 font-bold text-[#16A34A]"><Plus size={18}/>הוספת יום אימון</button></div></main>
}
function prescriptions(sets:string,repetitions:string):WorkoutSetPrescription[]{const count=Math.max(0,Math.min(12,Number.parseInt(sets,10)||0));return Array.from({length:count},(_,order)=>({id:uid("set"),order,repetitions:repetitions||undefined}));}
function Input({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <label className="text-xs font-bold text-[#3F433F]">{label}<input className="nutrition-input mt-1" type={type} min={type==="number"?"0":undefined} value={value} onChange={event=>onChange(event.target.value)}/></label>}
