import assert from "node:assert/strict";
import test from "node:test";
import { readFile } from "node:fs/promises";
import { normalizeExerciseName, stableWorkoutId } from "../lib/workouts/normalization.ts";
import { archiveWorkoutProgram, assignWorkout, createMemoryWorkoutRepository, duplicateWorkoutProgram, saveCompletedWorkout, startWorkoutSession } from "../lib/workouts/storage.ts";
import { exercisePerformance, getTodayWorkoutDay, workoutCompletionPercent, workoutVolume } from "../lib/workouts/progress.ts";
import type { ActiveWorkoutSession, ClientWorkoutAssignment, CompletedWorkout, WorkoutProgram, WorkoutRepositorySnapshot } from "../lib/workouts/types.ts";

const fixture:WorkoutProgram={id:"program-test",name:"TEST ONLY",sourceWorkbook:"test.xlsx",status:"active",official:true,equipment:[],days:[{id:"day-a",name:"A",order:0,exercises:[{id:"we-1",exerciseId:"ex-1",order:0,sets:"3",reps:"10"}]},{id:"day-b",name:"B",order:1,exercises:[]}]};
const initial:WorkoutRepositorySnapshot={exercises:[],programs:[fixture],clients:[],assignments:[],activeSessions:[],completedWorkouts:[],coachNotes:[],notifications:[],workoutPreferences:[],scheduleChanges:[]};
const assignment=(id:string,programId:string):ClientWorkoutAssignment=>({id,clientId:"client",programId,assignedAt:"2026-07-20T08:00:00Z",startDate:"2026-07-20",weeklyFrequency:3,status:"active"});
const session:ActiveWorkoutSession={id:"session",clientId:"client",assignmentId:"a1",programId:fixture.id,dayId:"day-a",startedAt:"2026-07-20T08:00:00Z",currentExerciseIndex:0,exerciseResults:[{workoutExerciseId:"we-1",exerciseId:"ex-1",skipped:false,completed:true,sets:[{id:"s1",order:0,weightKg:20,repetitions:10,completed:true}]}]};
const completion:CompletedWorkout={...session,id:"workout-1",completedAt:"2026-07-20T09:00:00Z",durationSeconds:3600,totalVolume:200};

test("exercise normalization merges punctuation, niqqud and Hebrew maqaf variants",()=>{assert.equal(normalizeExerciseName("  לְחִיצַת־חזה ״מוט״ "),"לחיצת חזה מוט");assert.equal(stableWorkoutId("exercise","same"),stableWorkoutId("exercise","same"))});
test("assignment replacement keeps one active assignment",()=>{const first=assignWorkout(initial,assignment("a1","p1"));const second=assignWorkout(first,assignment("a2","p2"));assert.equal(second.assignments.filter((item)=>item.status==="active").length,1);assert.equal(second.assignments.at(-1)?.programId,"p2")});
test("program duplication keeps content order and creates an editable copy",()=>{const copy=duplicateWorkoutProgram(fixture,"copy");assert.equal(copy.official,false);assert.equal(copy.duplicatedFromId,fixture.id);assert.deepEqual(copy.days.map((day)=>day.order),[0,1]);assert.equal(copy.days[0].exercises[0].exerciseId,"ex-1")});
test("official programs cannot be archived",()=>{assert.equal(archiveWorkoutProgram([fixture],fixture.id)[0].status,"active");const custom={...fixture,id:"custom",official:false};assert.equal(archiveWorkoutProgram([custom],custom.id)[0].status,"archived")});
test("only one active workout can exist per client",()=>{const once=startWorkoutSession(initial,session);const twice=startWorkoutSession(once,{...session,id:"other"});assert.equal(twice.activeSessions.length,1)});
test("completion is idempotent, closes active session and updates performance",()=>{const started=startWorkoutSession({...initial,assignments:[assignment("a1",fixture.id)]},session);const saved=saveCompletedWorkout(started,completion);const repeated=saveCompletedWorkout(saved,completion);assert.equal(repeated.completedWorkouts.length,1);assert.equal(repeated.activeSessions.length,0);assert.equal(workoutVolume(completion),200);assert.equal(exercisePerformance(repeated.completedWorkouts,"client","ex-1").sessions.length,1);assert.equal(getTodayWorkoutDay(fixture,repeated.completedWorkouts,"client")?.id,"day-b");assert.equal(workoutCompletionPercent(4,3),75)});
test("memory repository isolates and resets snapshots",()=>{const repository=createMemoryWorkoutRepository(initial);repository.save({...repository.load(),programs:[]});assert.equal(repository.load().programs.length,0);repository.reset();assert.equal(repository.load().programs.length,1)});
test("import audit confirms real approved programs, exercises and resolved references",async()=>{const audit=JSON.parse(await readFile(new URL("../reports/workout-import-audit.json",import.meta.url),"utf8"));assert.equal(audit.filesCopied.length,9);assert.ok(audit.programsImported>0);assert.ok(audit.uniqueExercisesImported>0);assert.equal(audit.unresolvedReferences.length,0);assert.ok(audit.videoLinksPreserved>0)});
test("Supabase workout schema covers catalog, assignments, sessions, sets and role policies",async()=>{const sql=await readFile(new URL("../supabase/migrations/202607200004_workout_persistence.sql",import.meta.url),"utf8");for(const table of ["workout_exercises","workout_programs","workout_program_days","workout_program_exercises","workout_assignments","workout_sessions","workout_session_exercises","workout_sets"])assert.match(sql,new RegExp(`create table public\\.${table}`));for(const rpc of ["assign_workout_program","save_active_workout","complete_workout"])assert.match(sql,new RegExp(`function public\\.${rpc}`));assert.match(sql,/enable row level security/)});
test("workout UI persistence no longer uses localStorage",async()=>{const provider=await readFile(new URL("../components/workouts/WorkoutProvider.tsx",import.meta.url),"utf8");const storage=await readFile(new URL("../lib/workouts/storage.ts",import.meta.url),"utf8");assert.doesNotMatch(provider,/localStorage|createBrowserWorkoutRepository/);assert.doesNotMatch(storage,/localStorage|start-workouts-v2/);assert.match(provider,/createSupabaseWorkoutRepository/)});
test("workout provider reloads and clears role-scoped state across login transitions",async()=>{const provider=await readFile(new URL("../components/workouts/WorkoutProvider.tsx",import.meta.url),"utf8");assert.match(provider,/usePathname/);assert.match(provider,/authScope/);assert.match(provider,/\},\[[^\]]*\bauthScope\b[^\]]*\brepository\b[^\]]*\]\)/);assert.match(provider,/setSnapshot\(emptyWorkoutSnapshot\)/);assert.match(provider,/setCurrentClientId\(""\)/)});
test("active workout uses the active assignment and derives a prescription summary when legacy text is absent",async()=>{const dashboard=await readFile(new URL("../components/workouts/client/DashboardWorkoutWidget.tsx",import.meta.url),"utf8");const today=await readFile(new URL("../components/workouts/client/TodayWorkout.tsx",import.meta.url),"utf8");const repository=await readFile(new URL("../lib/workouts/supabase-repository.ts",import.meta.url),"utf8");const sessionUi=await readFile(new URL("../components/workouts/client/WorkoutSession.tsx",import.meta.url),"utf8");assert.match(dashboard,/activeAssignmentFor\(snapshot\.assignments,currentClientId/);assert.match(dashboard,/role="status"/);assert.match(dashboard,/role="alert"/);assert.match(today,/activeAssignmentFor\(snapshot\.assignments,currentClientId,today\)/);assert.match(today,/role="status"/);assert.match(today,/role="alert"/);assert.match(repository,/sets:optionalText\(entry\.sets_text\)\?\?\(setPrescriptions\.length\?String\(setPrescriptions\.length\)/);assert.match(repository,/reps:optionalText\(entry\.reps_text\)\?\?\(repetitions\.length\?repetitions\.join/);assert.match(sessionUi,/value=\{current\.sets\?\?"לא הוגדר"\}/)});
test("workout timer and exercise effort are explicit and persist through programme notes",async()=>{const sessionUi=await readFile(new URL("../components/workouts/client/WorkoutSession.tsx",import.meta.url),"utf8");const editor=await readFile(new URL("../components/workouts/coach/CustomProgramEditor.tsx",import.meta.url),"utf8");const dayEditor=await readFile(new URL("../components/workouts/WorkoutDayPreview.tsx",import.meta.url),"utf8");const repository=await readFile(new URL("../lib/workouts/supabase-repository.ts",import.meta.url),"utf8");assert.match(sessionUi,/aria-label="טיימר אימון"/);assert.match(sessionUi,/label="רמת מאמץ"/);assert.match(editor,/רמת מאמץ \(RPE\)/);assert.match(dayEditor,/EffortPrescription/);assert.match(dayEditor,/length: 10/);assert.match(repository,/RPE יעד/);assert.match(repository,/serialiseExerciseNotes/)});
test("workout actions prevent duplicate start, assignment and completion saves",async()=>{const sessionUi=await readFile(new URL("../components/workouts/client/WorkoutSession.tsx",import.meta.url),"utf8");const coachUi=await readFile(new URL("../components/workouts/coach/CoachWorkoutProgram.tsx",import.meta.url),"utf8");assert.match(sessionUi,/const\[isStarting,setIsStarting\]=useState\(false\)/);assert.match(sessionUi,/disabled=\{!count\|\|starting\}/);assert.match(sessionUi,/const\[isCompleting,setIsCompleting\]=useState\(false\)/);assert.match(sessionUi,/disabled=\{saving\}/);assert.match(coachUi,/const\[submitting,setSubmitting\]=useState\(false\)/);assert.match(coachUi,/disabled=\{program\.status!=="active"\|\|submitting\}/)});
test("direct workout sessions wait for Supabase before returning not found",async()=>{const source=await readFile(new URL("../components/workouts/client/WorkoutSession.tsx",import.meta.url),"utf8");assert.match(source,/loading/);assert.match(source,/WorkoutLoadingState/);assert.ok(source.indexOf("if(loading)")<source.indexOf("if(!program||!day)notFound()"))});
test("all direct workout detail routes defer record checks until Supabase has loaded",async()=>{for(const path of ["app/workouts/history/[workoutId]/page.tsx","app/workouts/exercises/[exerciseId]/page.tsx","app/workouts/program/[programId]/page.tsx","app/workouts/[programId]/[dayId]/page.tsx","app/coach/workouts/[id]/page.tsx","app/coach/workouts/[id]/days/[dayId]/page.tsx"]){const source=await readFile(new URL(`../${path}`,import.meta.url),"utf8");assert.match(source,/WorkoutRouteReady/)}})
test("workout history and progress wait for Supabase and expose load errors",async()=>{for(const path of ["app/workouts/history/page.tsx","app/workouts/progress/page.tsx"]){const source=await readFile(new URL(`../${path}`,import.meta.url),"utf8");assert.match(source,/WorkoutRouteReady/)}const guard=await readFile(new URL("../components/workouts/WorkoutRouteReady.tsx",import.meta.url),"utf8");assert.match(guard,/persistenceError/);assert.match(guard,/role="alert"/)});
test("scheduled workout moves persist one date override and protect completed or conflicting sessions",async()=>{const sql=await readFile(new URL("../supabase/migrations/202607210001_workout_schedule_changes.sql",import.meta.url),"utf8");const guard=await readFile(new URL("../supabase/migrations/202607270004_prevent_same_day_workout_moves.sql",import.meta.url),"utf8");const today=await readFile(new URL("../components/workouts/client/TodayWorkout.tsx",import.meta.url),"utf8");for(const item of ["workout_schedule_changes","original_date","scheduled_date","moved_at","move_scheduled_workout","completed_workout_cannot_move","p_confirm_conflict","workout-morning-","workout-evening-"])assert.match(sql,new RegExp(item));assert.match(sql,/unique \(assignment_id, original_date\)/);assert.match(guard,/p_new_date <= p_original_date/);assert.match(today,/scheduledDate!==item\.originalDate/);assert.match(today,/העבר ליום אחר/);assert.match(today,/כבר קיים אימון אחר ביום הזה/);assert.match(today,/האימון הועבר בהצלחה/);assert.match(today,/האימון הושלם ולכן אינו ניתן להעברה/)});
