"use client";
/* eslint-disable react-hooks/purity */
import Link from "next/link";
import { notFound } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, ExternalLink, Play, RotateCcw, X } from "lucide-react";
import { useWorkouts } from "@/components/workouts/WorkoutProvider";
import WorkoutLoadingState from "@/components/workouts/WorkoutLoadingState";
import { exercisePerformance, workoutCompletionPercent, workoutVolume } from "@/lib/workouts/progress";
import type { ActiveExerciseResult, ActiveWorkoutSession, CompletedWorkout, ExerciseSetResult } from "@/lib/workouts/types";

const setCount=(value?:string)=>{const count=Number.parseInt(value??"",10);return Number.isFinite(count)&&count>0?Math.min(count,20):0};
const clock=(seconds:number)=>`${Math.floor(seconds/60).toString().padStart(2,"0")}:${(seconds%60).toString().padStart(2,"0")}`;

export default function WorkoutSession({programId,dayId}:{programId:string;dayId:string}){
  const{getProgram,getExercise,currentClientId,snapshot,loading,persistenceError,startSession,saveSession,cancelSession,completeSession}=useWorkouts();
  const program=getProgram(programId);const day=program?.days.find((item)=>item.id===dayId);
  const assignment=snapshot.assignments.find((item)=>item.clientId===currentClientId&&item.programId===programId&&item.status==="active");
  const anySession=snapshot.activeSessions.find((item)=>item.clientId===currentClientId);
  const session=anySession?.programId===programId&&anySession.dayId===dayId?anySession:undefined;
  const[now,setNow]=useState(()=>Date.now());const[summary,setSummary]=useState(false);const[warning,setWarning]=useState("");const[saved,setSaved]=useState<CompletedWorkout>();const[isStarting,setIsStarting]=useState(false);const[isCompleting,setIsCompleting]=useState(false);
  const ordered=useMemo(()=>[...(day?.exercises??[])].sort((a,b)=>a.order-b.order),[day]);
  useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[]);
  useEffect(()=>{const guard=(event:BeforeUnloadEvent)=>{if(session){event.preventDefault();event.returnValue=""}};window.addEventListener("beforeunload",guard);return()=>window.removeEventListener("beforeunload",guard)},[session]);
  if(loading)return <WorkoutLoadingState/>;
  if(!program||!day)notFound();
  const makeSession=():ActiveWorkoutSession=>({id:`session-${currentClientId}-${Date.now()}`,clientId:currentClientId,assignmentId:assignment?.id??"",programId,dayId,startedAt:new Date().toISOString(),currentExerciseIndex:0,exerciseResults:ordered.map((entry):ActiveExerciseResult=>({workoutExerciseId:entry.id,exerciseId:entry.exerciseId,skipped:false,completed:false,sets:Array.from({length:setCount(entry.sets)},(_,index):ExerciseSetResult=>({id:`${entry.id}-set-${index+1}`,prescriptionId:entry.setPrescriptions?.[index]?.id,order:index,completed:false}))}))});
  const begin=async()=>{if(isStarting)return;if(!assignment){setWarning("לא נמצאה הקצאת תוכנית פעילה.");return}if(anySession&&!session){setWarning("כבר קיים אימון פעיל אחר.");return}setIsStarting(true);try{if(!await startSession(makeSession()))setWarning("לא ניתן להתחיל שני אימונים במקביל.")}finally{setIsStarting(false)}};
  if(saved)return <Finished workout={saved}/>;
  if(!session)return <Start program={program.name} day={day.name} count={ordered.length} warning={warning} onStart={begin} starting={isStarting} programId={programId}/>;

  const current=ordered[Math.min(session.currentExerciseIndex,ordered.length-1)];const result=session.exerciseResults.find((item)=>item.workoutExerciseId===current?.id);if(!current||!result)return <main className="p-8 text-center text-white">אין תרגילים זמינים באימון זה.</main>;const difficulty=session.perceivedDifficulty??3;const energy=session.energy??3;
  const exercise=getExercise(result.exerciseId);const performance=exercisePerformance(snapshot.completedWorkouts,currentClientId,result.exerciseId);const previous=performance.sessions[0];const recentSets=performance.sessions.flatMap((item)=>item.sets.filter((set)=>set.completed));const bestWeight=Math.max(0,...recentSets.map((set)=>set.weightKg??0));
  const completedExercises=session.exerciseResults.filter((item)=>item.completed).length;const skipped=session.exerciseResults.filter((item)=>item.skipped).length;const completedSets=session.exerciseResults.flatMap((item)=>item.sets).filter((item)=>item.completed).length;const totalSets=session.exerciseResults.flatMap((item)=>item.sets).length;const elapsed=Math.max(0,Math.floor((now-new Date(session.startedAt).getTime())/1000));const rest=Math.max(0,Math.ceil(((session.restEndsAt?new Date(session.restEndsAt).getTime():0)-now)/1000));
  const persist=(patch:Partial<ActiveWorkoutSession>)=>saveSession({...session,...patch});
  const replaceResult=(next:ActiveExerciseResult,extra:Partial<ActiveWorkoutSession>={})=>persist({...extra,exerciseResults:session.exerciseResults.map((item)=>item.workoutExerciseId===next.workoutExerciseId?next:item)});
  const updateSet=(set:ExerciseSetResult,patch:Partial<ExerciseSetResult>)=>{const nextSet={...set,...patch};const nextResult={...result,sets:result.sets.map((item)=>item.id===set.id?nextSet:item),completed:result.sets.every((item)=>item.id===set.id?nextSet.completed:item.completed)};const restSeconds=patch.completed?Number.parseInt(current.rest??"",10):0;replaceResult(nextResult,Number.isFinite(restSeconds)&&restSeconds>0?{restEndsAt:new Date(Date.now()+restSeconds*1000).toISOString()}:{});};
  const finish=()=>{if(session.exerciseResults.some((item)=>!item.completed&&!item.skipped)&&!warning){setWarning("נותרו תרגילים שלא הושלמו. לחיצה נוספת תשמור אותם כחלקיים.");return}setWarning("");setSummary(true)};
  const complete=async()=>{if(isCompleting)return;setIsCompleting(true);try{const completedAt=new Date().toISOString();const workout:CompletedWorkout={id:`workout-${session.id}`,clientId:session.clientId,assignmentId:session.assignmentId,programId,dayId,startedAt:session.startedAt,completedAt,durationSeconds:Math.max(1,Math.floor((Date.now()-new Date(session.startedAt).getTime())/1000)),exerciseResults:session.exerciseResults,workoutNote:session.workoutNote?.trim()||undefined,perceivedDifficulty:difficulty,energy,totalVolume:workoutVolume(session.exerciseResults)};if(await completeSession(workout))setSaved(workout);else setWarning("האימון לא נשמר ב-Supabase. יש לנסות שוב.")}finally{setIsCompleting(false)}};
  if(summary)return <CompletionForm elapsed={elapsed} exercises={`${completedExercises}/${ordered.length}`} sets={`${completedSets}/${totalSets}`} skipped={skipped} volume={workoutVolume(session.exerciseResults)} note={session.workoutNote??""} setNote={(workoutNote)=>persist({workoutNote})} difficulty={difficulty} setDifficulty={(perceivedDifficulty)=>persist({perceivedDifficulty})} energy={energy} setEnergy={(nextEnergy)=>persist({energy:nextEnergy})} warning={warning||persistenceError} onSave={complete} saving={isCompleting} onBack={()=>setSummary(false)}/>;

  return <main className="px-4 py-6 text-white sm:px-6"><div className="mx-auto max-w-4xl">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold text-[#D4AF37]">{program.name}</p><h1 className="mt-1 text-2xl font-black">{day.name}</h1></div><div className="text-left"><strong className="font-mono text-xl">{clock(elapsed)}</strong><p className="text-xs text-zinc-500">זמן אימון</p></div></header>
    <div className="mt-4 h-2 overflow-hidden rounded-full bg-zinc-800"><div className="h-full bg-[#D4AF37]" style={{width:`${workoutCompletionPercent(totalSets,completedSets)}%`}}/></div>
    {rest>0&&<RestTimer seconds={rest} onAdd={()=>persist({restEndsAt:new Date(Date.now()+(rest+30)*1000).toISOString()})} onSkip={()=>persist({restEndsAt:undefined})}/>} 
    <article className="mt-5 rounded-[26px] border border-[#292929] bg-[#151515] p-5">
      <div className="flex items-start justify-between gap-3"><div><span className="text-xs text-zinc-500">תרגיל {session.currentExerciseIndex+1} מתוך {ordered.length}</span><h2 className="mt-1 text-2xl font-black">{exercise?.name??"פרטי תרגיל חסרים"}</h2><p className="mt-1 text-sm text-zinc-500">{[exercise?.primaryMuscleGroup,exercise?.equipment].filter(Boolean).join(" · ")||"פרטי ציוד לא סופקו במקור"}</p></div>{exercise?.video?<a href={exercise.video.url} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-[#D4AF37]/30 px-3 text-[#D4AF37]">וידאו<ExternalLink size={15}/></a>:<span className="text-xs text-zinc-600">אין וידאו במקור</span>}</div>
      <dl className="mt-4 grid grid-cols-3 gap-3"><Value label="סטים" value={current.sets??"לא הוגדר"}/><Value label="חזרות" value={current.reps??"לא הוגדר"}/><Value label="מנוחה" value={current.rest??"לא הוגדר"}/></dl>
      {(current.notes||exercise?.executionNotes)&&<p className="mt-4 rounded-xl bg-black/20 p-3 text-sm text-zinc-400">{current.notes||exercise?.executionNotes}</p>}
      <PreviousPerformance previous={previous} bestWeight={bestWeight} recent={performance.sessions.slice(0,3)}/>
      <div className="mt-5 space-y-3">{result.sets.map((set,index)=><SetEditor key={set.id} set={set} index={index} target={current.setPrescriptions?.[index]?.repetitions??current.reps} onUpdate={(patch)=>updateSet(set,patch)}/>)}</div>
      <div className="mt-4 grid grid-cols-2 gap-3"><button onClick={()=>replaceResult({...result,skipped:!result.skipped,completed:false})} className="min-h-12 rounded-2xl border border-[#444]">{result.skipped?"החזרת התרגיל":"דילוג על התרגיל"}</button><button onClick={()=>replaceResult({...result,completed:true,skipped:false,sets:result.sets.map((set)=>({...set,completed:true,completedAt:set.completedAt??new Date().toISOString()}))})} className="min-h-12 rounded-2xl border border-[#D4AF37]/40 text-[#D4AF37]">השלמת התרגיל</button></div>
      <Link href={`/workouts/exercises/${result.exerciseId}?programId=${programId}&dayId=${dayId}`} className="mt-3 flex min-h-11 items-center justify-center text-sm text-zinc-400">כל היסטוריית התרגיל</Link>
    </article>
    <nav className="mt-4 grid grid-cols-2 gap-3"><button disabled={session.currentExerciseIndex===0} onClick={()=>persist({currentExerciseIndex:session.currentExerciseIndex-1})} className="min-h-12 rounded-2xl border border-[#333] disabled:opacity-30">הקודם</button><button disabled={session.currentExerciseIndex===ordered.length-1} onClick={()=>persist({currentExerciseIndex:session.currentExerciseIndex+1})} className="min-h-12 rounded-2xl border border-[#333] disabled:opacity-30">הבא</button></nav>
    {(warning||persistenceError)&&<p role="alert" className="mt-4 rounded-xl border border-amber-400/30 bg-amber-400/10 p-3 text-sm text-amber-100">{warning||persistenceError}</p>}
    <button onClick={finish} className="mt-5 min-h-14 w-full rounded-2xl bg-[#D4AF37] font-black text-black">סיום אימון</button>
    <button onClick={async()=>{if(window.confirm("לבטל את האימון הפעיל? הנתונים יימחקו."))await cancelSession(currentClientId)}} className="mt-2 flex min-h-11 w-full items-center justify-center gap-2 text-sm text-red-300"><X size={16}/>ביטול האימון</button>
  </div></main>;
}

function Start({program,day,count,warning,onStart,starting,programId}:{program:string;day:string;count:number;warning:string;onStart:()=>void|Promise<void>;starting:boolean;programId:string}){return <main className="grid min-h-[70vh] place-items-center px-4 text-center text-white"><section className="max-w-lg rounded-[28px] border border-[#292929] bg-[#151515] p-8"><Play className="mx-auto text-[#D4AF37]" size={46}/><p className="mt-5 text-xs font-bold text-[#D4AF37]">{program}</p><h1 className="mt-2 text-3xl font-black">{day}</h1><p className="mt-3 text-sm text-zinc-400">{count} תרגילים לפי סדר המקור. ההתקדמות נשמרת ב-Supabase.</p>{warning&&<p role="alert" className="mt-4 text-red-300">{warning}</p>}<button onClick={onStart} disabled={!count||starting} className="mt-6 min-h-14 w-full rounded-2xl bg-[#D4AF37] font-black text-black disabled:opacity-40">{starting?"מתחילים…":"התחלת אימון"}</button><Link href={`/workouts/program/${programId}`} className="mt-3 inline-flex min-h-11 items-center">חזרה לתוכנית</Link></section></main>}
function PreviousPerformance({previous,bestWeight,recent}:{previous?:{date:string;sets:readonly ExerciseSetResult[];volume:number};bestWeight:number;recent:readonly {workoutId:string;date:string;sets:readonly ExerciseSetResult[];volume:number}[]}){return <section className="mt-4 rounded-2xl border border-[#3A321B] bg-[#17150F] p-4"><div className="flex justify-between gap-3"><h3 className="font-black">ביצוע קודם</h3>{bestWeight>0&&<span className="text-xs text-[#D4AF37]">שיא משקל: {bestWeight} ק״ג</span>}</div>{previous?<><p className="mt-2 text-xs text-zinc-500">{new Date(previous.date).toLocaleDateString("he-IL",{timeZone:"Asia/Jerusalem"})}</p><p className="mt-2 text-sm">{previous.sets.map((set)=>`${set.weightKg??0} ק״ג × ${set.repetitions??0}`).join(" · ")}</p>{recent.length>1&&<details className="mt-2 text-xs text-zinc-500"><summary className="cursor-pointer">ביצועים אחרונים</summary>{recent.map((item)=><p key={item.workoutId} className="mt-2">{new Date(item.date).toLocaleDateString("he-IL",{timeZone:"Asia/Jerusalem"})} · נפח {item.volume}</p>)}</details>}</>:<p className="mt-2 text-sm text-zinc-500">זהו הביצוע הראשון שנרשם לתרגיל.</p>}</section>}
function SetEditor({set,index,target,onUpdate}:{set:ExerciseSetResult;index:number;target?:string;onUpdate:(patch:Partial<ExerciseSetResult>)=>void}){return <section className={`rounded-2xl border p-4 ${set.completed?"border-emerald-400/30 bg-emerald-400/[.04]":"border-[#303030]"}`}><div className="flex justify-between"><strong>סט {index+1}</strong><span className="text-xs text-zinc-500">יעד: {target??"—"}</span></div><div className="mt-3 grid grid-cols-2 gap-3"><Field label="משקל (ק״ג)" value={set.weightKg} onChange={(weightKg)=>onUpdate({weightKg})}/><Field label="חזרות בפועל" value={set.repetitions} step="1" onChange={(repetitions)=>onUpdate({repetitions})}/></div><label className="mt-3 block text-xs font-bold">הערת סט<input className="nutrition-input mt-2" value={set.notes??""} onChange={(event)=>onUpdate({notes:event.target.value||undefined})}/></label><button onClick={()=>onUpdate({completed:!set.completed,completedAt:!set.completed?new Date().toISOString():undefined})} className={`mt-3 min-h-11 w-full rounded-xl font-bold ${set.completed?"border border-emerald-400/30 text-emerald-300":"bg-[#D4AF37] text-black"}`}>{set.completed?<><RotateCcw className="ml-2 inline" size={15}/>ביטול השלמת סט</>:"השלמת סט"}</button></section>}
function RestTimer({seconds,onAdd,onSkip}:{seconds:number;onAdd:()=>void;onSkip:()=>void}){return <section className="mt-4 flex items-center justify-between rounded-2xl border border-[#D4AF37]/30 bg-[#D4AF37]/10 p-4"><div><p className="text-xs text-zinc-400">מנוחה</p><strong className="font-mono text-2xl">{clock(seconds)}</strong></div><div className="flex gap-2"><button onClick={onAdd} className="min-h-11 rounded-xl border border-[#D4AF37]/30 px-3">+30 שנ׳</button><button onClick={onSkip} className="min-h-11 rounded-xl bg-[#D4AF37] px-3 font-bold text-black">דלג</button></div></section>}
function CompletionForm({elapsed,exercises,sets,skipped,volume,note,setNote,difficulty,setDifficulty,energy,setEnergy,warning,onSave,saving,onBack}:{elapsed:number;exercises:string;sets:string;skipped:number;volume:number;note:string;setNote:(value:string)=>void;difficulty:1|2|3|4|5;setDifficulty:(value:1|2|3|4|5)=>void;energy:1|2|3|4|5;setEnergy:(value:1|2|3|4|5)=>void;warning:string;onSave:()=>void|Promise<void>;saving:boolean;onBack:()=>void}){return <main className="px-4 py-8 text-white"><section className="mx-auto max-w-2xl rounded-[28px] border border-[#3A321B] bg-[#17150F] p-6"><h1 className="text-3xl font-black">סיכום לפני שמירה</h1><dl className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-5"><Value label="משך" value={clock(elapsed)}/><Value label="תרגילים" value={exercises}/><Value label="סטים" value={sets}/><Value label="נפח" value={`${volume} ק״ג`}/><Value label="דולגו" value={String(skipped)}/></dl><label className="mt-5 block text-sm font-bold">הערת אימון<textarea className="nutrition-input mt-2 min-h-24" value={note} onChange={(event)=>setNote(event.target.value)}/></label><Rating label="קושי מורגש" value={difficulty} onChange={setDifficulty}/><Rating label="רמת אנרגיה" value={energy} onChange={setEnergy}/>{warning&&<p role="alert" className="mt-4 text-sm text-red-300">{warning}</p>}<button onClick={onSave} disabled={saving} className="mt-6 min-h-14 w-full rounded-2xl bg-[#D4AF37] font-black text-black disabled:opacity-40">{saving?"שומרים…":"שמירת האימון"}</button><button onClick={onBack} disabled={saving} className="mt-2 min-h-11 w-full disabled:opacity-40">חזרה לאימון</button></section></main>}
function Finished({workout}:{workout:CompletedWorkout}){const exercises=workout.exerciseResults.filter((item)=>item.completed).length;const sets=workout.exerciseResults.flatMap((item)=>item.sets).filter((item)=>item.completed).length;const skipped=workout.exerciseResults.filter((item)=>item.skipped).length;return <main className="grid min-h-[70vh] place-items-center px-4 text-center text-white"><section className="w-full max-w-2xl"><CheckCircle2 className="mx-auto text-emerald-400" size={56}/><h1 className="mt-5 text-4xl font-black">האימון נשמר</h1><dl className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-5"><Value label="משך" value={clock(workout.durationSeconds)}/><Value label="תרגילים" value={String(exercises)}/><Value label="סטים" value={String(sets)}/><Value label="נפח" value={`${workout.totalVolume} ק״ג`}/><Value label="דולגו" value={String(skipped)}/></dl><div className="mt-6 flex justify-center gap-3"><Link href="/workouts" className="rounded-2xl bg-[#D4AF37] px-5 py-3 font-black text-black">בית האימונים</Link><Link href={`/workouts/history/${workout.id}`} className="rounded-2xl border border-[#333] px-5 py-3 font-bold">פרטי האימון</Link></div></section></main>}
function Value({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-black/25 p-3"><dt className="text-xs text-zinc-500">{label}</dt><dd className="mt-1 font-black">{value}</dd></div>}
function Field({label,value,step="0.1",onChange}:{label:string;value?:number;step?:string;onChange:(value:number|undefined)=>void}){return <label className="text-xs font-bold">{label}<input className="nutrition-input mt-2" type="number" min="0" step={step} value={value??""} onChange={(event)=>onChange(event.target.value===""?undefined:Number(event.target.value))}/></label>}
function Rating({label,value,onChange}:{label:string;value:1|2|3|4|5;onChange:(value:1|2|3|4|5)=>void}){return <fieldset className="mt-5"><legend className="text-sm font-bold">{label}</legend><div className="mt-2 grid grid-cols-5 gap-2">{([1,2,3,4,5] as const).map((item)=><button type="button" key={item} onClick={()=>onChange(item)} aria-pressed={value===item} className={`min-h-11 rounded-xl ${value===item?"bg-[#D4AF37] font-black text-black":"border border-[#333]"}`}>{item}</button>)}</div></fieldset>}
