"use client";
import Link from "next/link";
import { Search, SlidersHorizontal, X } from "lucide-react";
import { useDeferredValue, useMemo, useState } from "react";
import type { Food, FoodSort } from "@/lib/foods";
import { ALL_CATEGORIES, queryFoods } from "@/lib/foods/repository";

export default function FoodDatabase({ foods }: { foods: readonly Food[] }) {
  const [search, setSearch] = useState(""); const [category, setCategory] = useState(ALL_CATEGORIES); const [sort, setSort] = useState<FoodSort>("relevant"); const deferredSearch = useDeferredValue(search);
  const categories = useMemo(() => [ALL_CATEGORIES, ...new Set(foods.map((food) => food.category))].sort((a, b) => a === ALL_CATEGORIES ? -1 : b === ALL_CATEGORIES ? 1 : a.localeCompare(b, "he")), [foods]);
  const visible = useMemo(() => queryFoods(foods, { search: deferredSearch, category, sort }), [foods, deferredSearch, category, sort]);
  const clear = () => { setSearch(""); setCategory(ALL_CATEGORIES); setSort("relevant"); };
  return <section className="food-database" aria-busy={search !== deferredSearch}><header className="food-database__header"><div><span className="food-database__eyebrow">START FOOD DATABASE</span><h1 className="food-database__title">מאגר מזונות</h1><p className="food-database__description">חיפוש לפי שם, מותג, קטגוריה או ברקוד</p><p className="mt-3 text-xs text-zinc-500">{foods.length} מוצרים מהמאגר הרשמי</p></div><div className="food-database__count"><strong>{visible.length}</strong><span>תוצאות</span></div></header><div className="grid gap-3 rounded-[22px] border border-[#2b2b2b] bg-[#151515] p-3 sm:grid-cols-[minmax(0,1fr)_220px]"><label className="relative"><span className="sr-only">חיפוש מזונות</span><Search className="absolute right-4 top-4 text-[#D4AF37]" size={18}/><input className="nutrition-input pr-11" type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="חיפוש מזון..." autoComplete="off"/>{search && <button type="button" onClick={() => setSearch("")} aria-label="ניקוי חיפוש" className="absolute left-3 top-3 rounded-xl p-2 text-zinc-500 hover:text-white"><X size={18}/></button>}</label><label className="flex items-center gap-2 text-xs text-zinc-500"><SlidersHorizontal size={17}/>מיון<select className="nutrition-input" value={sort} onChange={(event) => setSort(event.target.value as FoodSort)}><option value="relevant">רלוונטיות</option><option value="protein-high">חלבון: גבוה לנמוך</option><option value="calories-low">קלוריות: נמוך לגבוה</option><option value="calories-high">קלוריות: גבוה לנמוך</option><option value="alphabetical">א׳–ת׳</option></select></label></div><div className="food-categories" aria-label="סינון לפי קטגוריה">{categories.map((item) => <button key={item} type="button" aria-pressed={category === item} className={category === item ? "food-category active" : "food-category"} onClick={() => setCategory(item)}>{item}</button>)}</div>{visible.length ? <div className="food-list">{visible.map((food) => <FoodCard key={food.id} food={food}/>)}</div> : <div className="food-empty-state"><Search className="mx-auto mb-3 text-zinc-600" size={38}/><h2>לא נמצאו מוצרים</h2><p>אפשר לנסות שם, מותג, ברקוד או קטגוריה אחרים.</p><button type="button" onClick={clear}>ניקוי הסינונים</button></div>}</section>;
}
export function FoodCard({ food }: { food: Food }) { return <article className="food-card"><div className="food-card__top"><div><span className="food-card__category">{food.category}</span><h2 className="food-card__name">{food.name}</h2>{food.brand && <p className="food-card__brand">{food.brand}</p>}</div><div className="food-card__calories"><strong>{food.calories}</strong><span>קלוריות</span></div></div><div className="food-card__macros"><Macro label="חלבון" value={food.protein}/><Macro label="פחמימה" value={food.carbs}/><Macro label="שומן" value={food.fat}/></div><div className="food-card__footer flex items-center justify-between gap-3"><span>{food.servingLabel}</span><Link href={`/foods/${food.id}`} className="font-bold text-[#D4AF37]">פרטים</Link></div></article>; }
function Macro({ label, value }: { label: string; value?: number }) { return <div className="food-macro"><span>{label}</span><strong>{value === undefined ? "—" : `${value} גרם`}</strong></div>; }
