import type { ActiveExerciseResult, ClientWorkoutAssignment, CompletedWorkout, ExercisePerformanceHistory, WorkoutDay, WorkoutProgram } from "./types.ts";
export function getTodayWorkoutDay(program:WorkoutProgram,completedWorkouts:readonly CompletedWorkout[],clientId:string):WorkoutDay|undefined{if(!program.days.length)return undefined;const completed=completedWorkouts.filter((item)=>item.clientId===clientId&&item.programId===program.id).length;return [...program.days].sort((a,b)=>a.order-b.order)[completed%program.days.length]}
export function workoutCompletionPercent(total:number,completed:number):number{return total<=0?0:Math.min(100,Math.max(0,Math.round(completed/total*100)))}
export function workoutVolume(workout:Pick<CompletedWorkout,"exerciseResults">|readonly ActiveExerciseResult[]):number{const results:readonly ActiveExerciseResult[]=Array.isArray(workout)?workout:(workout as Pick<CompletedWorkout,"exerciseResults">).exerciseResults;return results.flatMap((exercise)=>exercise.sets).filter((set)=>set.completed).reduce((sum,set)=>sum+(set.weightKg??0)*(set.repetitions??0),0)}
export function exercisePerformance(workouts:readonly CompletedWorkout[],clientId:string,exerciseId:string):ExercisePerformanceHistory{const sessions=workouts.filter((workout)=>workout.clientId===clientId&&workout.exerciseResults.some((entry)=>entry.exerciseId===exerciseId)).map((workout)=>{const sets=workout.exerciseResults.find((entry)=>entry.exerciseId===exerciseId)?.sets??[];return{workoutId:workout.id,date:workout.completedAt,sets,volume:sets.reduce((sum,set)=>sum+(set.weightKg??0)*(set.repetitions??0),0)}}).sort((a,b)=>b.date.localeCompare(a.date));return{exerciseId,sessions}}
export function activeAssignmentFor(assignments:readonly ClientWorkoutAssignment[],clientId:string,date:string):ClientWorkoutAssignment|undefined{return[...assignments].reverse().find((item)=>item.clientId===clientId&&item.status==="active"&&item.startDate<=date&&(!item.endDate||item.endDate>=date))}
export function assignmentState(assignment:ClientWorkoutAssignment,date:string):"not-started"|"expired"|"paused"|"completed"|"active"{if(assignment.status==="paused")return"paused";if(assignment.status==="completed"||assignment.status==="archived")return"completed";if(assignment.startDate>date)return"not-started";if(assignment.endDate&&assignment.endDate<date)return"expired";return"active"}
const dateOnly=(value:string)=>value.slice(0,10);
export function adherenceSummary(assignmentOrWorkouts:ClientWorkoutAssignment|readonly CompletedWorkout[],workoutsOrAssignment:readonly CompletedWorkout[]|ClientWorkoutAssignment|undefined,todayValue:string|Date){const legacy=Array.isArray(assignmentOrWorkouts);const assignment=(legacy?workoutsOrAssignment:assignmentOrWorkouts) as ClientWorkoutAssignment|undefined;const workouts=(legacy?assignmentOrWorkouts:workoutsOrAssignment) as readonly CompletedWorkout[];if(!assignment)return{completed:0,expected:0,missed:0,percent:0};const today=typeof todayValue==="string"?todayValue:todayValue.toISOString().slice(0,10);const start=new Date(`${assignment.startDate}T00:00:00Z`);const end=new Date(`${today}T00:00:00Z`);const elapsedDays=Math.max(1,Math.floor((end.getTime()-start.getTime())/86400000)+1);const expected=Math.max(1,Math.ceil(elapsedDays/7*assignment.weeklyFrequency));const completed=workouts.filter((item)=>item.assignmentId===assignment.id&&dateOnly(item.completedAt)>=assignment.startDate&&dateOnly(item.completedAt)<=today).length;return{completed,expected,missed:Math.max(0,expected-completed),percent:Math.min(100,Math.round(completed/expected*100))}}
export function workoutStreak(workouts:readonly CompletedWorkout[],clientId:string):number{const dates=[...new Set(workouts.filter((item)=>item.clientId===clientId).map((item)=>dateOnly(item.completedAt)))].sort((a,b)=>b.localeCompare(a));if(!dates.length)return 0;let streak=1;for(let i=1;i<dates.length;i++){const previous=new Date(`${dates[i-1]}T00:00:00Z`);const current=new Date(`${dates[i]}T00:00:00Z`);if((previous.getTime()-current.getTime())/86400000>7)break;streak++}return streak}
export function trend(current?:number,previous?:number):"up"|"down"|"stable"|"insufficient-data"{if(current===undefined||previous===undefined)return"insufficient-data";if(current>previous)return"up";if(current<previous)return"down";return"stable"}
