import type { WorkoutPersistenceRepository } from "./contracts.ts";
import type { ActiveWorkoutSession, AssignmentStatus, ClientWorkoutAssignment, CoachWorkoutNote, CompletedWorkout, WorkoutNotification, WorkoutPreferences, WorkoutProgram, WorkoutRepositorySnapshot } from "./types.ts";
export function createMemoryWorkoutRepository(initial:WorkoutRepositorySnapshot):WorkoutPersistenceRepository{let state=structuredClone(initial);return{load:()=>structuredClone(state),save:(next)=>{state=structuredClone(next)},reset:()=>{state=structuredClone(initial)}}}
export function assignWorkout(snapshot:WorkoutRepositorySnapshot,assignment:ClientWorkoutAssignment):WorkoutRepositorySnapshot{if(snapshot.assignments.some((item)=>item.clientId===assignment.clientId&&item.programId===assignment.programId&&item.status==="active"))return snapshot;const assignments=snapshot.assignments.map((item)=>item.clientId===assignment.clientId&&item.status==="active"?{...item,status:"completed" as const}:item);const notification:WorkoutNotification={id:`notification-${assignment.id}`,clientId:assignment.clientId,type:"assignment",createdAt:assignment.assignedAt,read:false};return{...snapshot,assignments:[...assignments,assignment],notifications:[...snapshot.notifications,notification]}}
export function updateAssignmentStatus(snapshot:WorkoutRepositorySnapshot,id:string,status:AssignmentStatus):WorkoutRepositorySnapshot{const target=snapshot.assignments.find((item)=>item.id===id);if(!target)return snapshot;const assignments=snapshot.assignments.map((item)=>item.id===id?{...item,status}:status==="active"&&item.clientId===target.clientId&&item.status==="active"?{...item,status:"completed" as const}:item);return{...snapshot,assignments,activeSessions:status==="active"?snapshot.activeSessions:snapshot.activeSessions.filter((session)=>session.assignmentId!==id)}}
export function duplicateWorkoutProgram(program:WorkoutProgram,id:string):WorkoutProgram{return{...program,id,name:`${program.name} — עותק`,status:"active",official:false,duplicatedFromId:program.id,days:program.days.map((day,dayIndex)=>({...day,id:`${id}-day-${dayIndex}`,exercises:day.exercises.map((exercise,index)=>({...exercise,id:`${id}-exercise-${dayIndex}-${index}`,setPrescriptions:exercise.setPrescriptions?.map((set,setIndex)=>({...set,id:`${id}-set-${dayIndex}-${index}-${setIndex}`}))}))}))}}
export function archiveWorkoutProgram(programs:readonly WorkoutProgram[],id:string):WorkoutProgram[]{return programs.map((program)=>program.id===id&&!program.official?{...program,status:"archived"}:program)}
// An approved programme is editable by a coach like any other, so this no longer
// drops the save on the floor when official is set. What official still means is
// that the flag itself, and the ownership, are the database's to decide -
// save_workout_program_tree keeps both out of its update list.
export function saveCustomWorkoutProgram(snapshot:WorkoutRepositorySnapshot,program:WorkoutProgram):WorkoutRepositorySnapshot{return{...snapshot,programs:snapshot.programs.map((item)=>item.id===program.id?{...program,official:item.official}:item)}}
export function startWorkoutSession(snapshot:WorkoutRepositorySnapshot,session:ActiveWorkoutSession):WorkoutRepositorySnapshot{if(snapshot.activeSessions.some((item)=>item.clientId===session.clientId))return snapshot;return{...snapshot,activeSessions:[...snapshot.activeSessions,session]}}
export function saveActiveWorkoutSession(snapshot:WorkoutRepositorySnapshot,session:ActiveWorkoutSession):WorkoutRepositorySnapshot{return{...snapshot,activeSessions:snapshot.activeSessions.map((item)=>item.id===session.id?session:item)}}
export function cancelWorkoutSession(snapshot:WorkoutRepositorySnapshot,clientId:string):WorkoutRepositorySnapshot{return{...snapshot,activeSessions:snapshot.activeSessions.filter((item)=>item.clientId!==clientId)}}
export function saveCompletedWorkout(snapshot:WorkoutRepositorySnapshot,workout:CompletedWorkout):WorkoutRepositorySnapshot{if(snapshot.completedWorkouts.some((item)=>item.id===workout.id))return snapshot;const notification:WorkoutNotification={id:`notification-${workout.id}`,clientId:workout.clientId,type:"completed-workout",createdAt:workout.completedAt,read:false};return{...snapshot,activeSessions:snapshot.activeSessions.filter((item)=>item.clientId!==workout.clientId),completedWorkouts:[...snapshot.completedWorkouts,workout],notifications:[...snapshot.notifications,notification]}}
export function saveCoachWorkoutNote(snapshot:WorkoutRepositorySnapshot,note:CoachWorkoutNote):WorkoutRepositorySnapshot{return{...snapshot,coachNotes:snapshot.coachNotes.some((item)=>item.id===note.id)?snapshot.coachNotes.map((item)=>item.id===note.id?note:item):[...snapshot.coachNotes,note]}}
export function saveWorkoutPreferences(snapshot:WorkoutRepositorySnapshot,preferences:WorkoutPreferences):WorkoutRepositorySnapshot{return{...snapshot,workoutPreferences:snapshot.workoutPreferences.some((item)=>item.clientId===preferences.clientId)?snapshot.workoutPreferences.map((item)=>item.clientId===preferences.clientId?preferences:item):[...snapshot.workoutPreferences,preferences]}}
export function recordMissedWorkoutNotification(snapshot:WorkoutRepositorySnapshot,clientId:string,date:string):WorkoutRepositorySnapshot{const id=`notification-missed-${clientId}-${date}`;if(snapshot.notifications.some((item)=>item.id===id))return snapshot;return{...snapshot,notifications:[...snapshot.notifications,{id,clientId,type:"missed-workout",createdAt:`${date}T20:00:00.000Z`,read:false}]}}
