"use server";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getSupabaseConfig } from "@/lib/supabase/env";
import { cookies, headers } from "next/headers";
import { DEVICE_COOKIE } from "@/lib/auth/device";
import { isAllowedE2ETestEmail } from "@/lib/auth/test-login";
import { destinationForRole } from "@/lib/auth/authorization";
import { returnPathForRole, safeReturnPath } from "@/lib/auth/return-path";
import { siteUrlForRedirect } from "@/lib/auth/site-url";
import { consumeRateLimit } from "@/lib/security/rate-limit";
export type LoginState = Readonly<{ status: "idle" | "sent" | "error"; message?: string; redirectTo?:string }>;
export async function requestTestPasswordLogin(_previous: LoginState, formData: FormData): Promise<LoginState> { const email=String(formData.get("email")??"").trim().toLowerCase(); const password=String(formData.get("password")??""); if(!isAllowedE2ETestEmail(email)||!password)return{status:"error",message:"התחברות בדיקה אינה זמינה לחשבון זה."}; try { const supabase=await createSupabaseServerClient(); const {data,error}=await supabase.auth.signInWithPassword({email,password}); if(error||!data.user)return{status:"error",message:"פרטי ההתחברות לבדיקה אינם תקינים."}; const {data:profile,error:profileError}=await supabase.from("profiles").select("role,status,is_test_account").eq("id",data.user.id).single(); if(profileError||!profile||profile.status!=="active"||!profile.is_test_account) { await supabase.auth.signOut({scope:"local"}); return {status:"error",message:"החשבון אינו חשבון בדיקה פעיל."}; } if(profile.role==="client"){const deviceId=(await cookies()).get(DEVICE_COOKIE)?.value; if(!deviceId){await supabase.auth.signOut({scope:"local"});return{status:"error",message:"לא ניתן לאמת את המכשיר. נסו שוב."};}const userAgent=(await headers()).get("user-agent")?.slice(0,120)||"דפדפן";const{error:deviceError}=await supabase.rpc("activate_current_device",{p_device_id:deviceId,p_device_name:userAgent});if(deviceError){await supabase.auth.signOut({scope:"local"});return{status:"error",message:"לא ניתן לאמת את המכשיר. נסו שוב."};}} const requested=String(formData.get("next")??""); return{status:"sent",message:"התחברת. מעבירים אותך לחשבון הבדיקה…",redirectTo:returnPathForRole(requested,profile.role)??destinationForRole(profile.role)}; } catch { return{status:"error",message:"לא ניתן להתחבר כרגע."}; } }
export async function requestMagicLink(_previous: LoginState, formData: FormData): Promise<LoginState> { const email = String(formData.get("email") ?? "").trim().toLowerCase(); if (!/^\S+@\S+\.\S+$/.test(email)) return { status: "error", message: "יש להזין כתובת אימייל תקינה." }; const inbound=await headers();const address=(inbound.get("x-forwarded-for")?.split(",")[0]??inbound.get("x-real-ip")??"unknown").trim();const[emailAllowed,addressAllowed]=await Promise.all([consumeRateLimit({action:"magic_link_email",subject:email,windowSeconds:900,limit:3}),consumeRateLimit({action:"magic_link_ip",subject:address,windowSeconds:900,limit:20})]);if(!emailAllowed||!addressAllowed)return{status:"error",message:"נשלחו יותר מדי בקשות. יש להמתין ולנסות שוב."}; if (!getSupabaseConfig()) return { status: "error", message: "שירות ההתחברות עדיין לא הוגדר בסביבה זו." }; const siteUrl = await siteUrlForRedirect(); if (!siteUrl) return { status: "error", message: "כתובת האתר עדיין לא הוגדרה בסביבה זו." }; const requested=safeReturnPath(String(formData.get("next")??"")) ?? "/"; const returnQuery=`?next=${encodeURIComponent(requested)}`; try { const supabase = await createSupabaseServerClient(); const { error } = await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo: `${siteUrl}/auth/confirm-link${returnQuery}`, shouldCreateUser: false } }); if (error) { console.error("Magic Link request failed", { code: error.code, status: error.status }); return { status: "error", message: error.message.includes("rate") ? "נשלחו יותר מדי בקשות. יש להמתין ולנסות שוב." : "לא ניתן לשלוח קישור כרגע. ודאו שהחשבון קיים ונסו שוב." }; } return { status: "sent", message: "קישור התחברות נשלח. אפשר לבדוק את תיבת האימייל." }; } catch { return { status: "error", message: "שירות ההתחברות אינו זמין כרגע." }; } }
