"use client";

import { useMemo, useState } from "react";
import { ClipboardCheck, Plus } from "lucide-react";
import { useClientData } from "./ClientDataProvider";
import { getAttentionFlags, sortCheckIns } from "@/lib/check-ins/calculations";
import type { Rating } from "@/lib/check-ins/types";

const flagLabels = { "missing-update": "חסר עדכון שבועי", "low-hunger": "דירוג רעב נמוך", "low-sleep": "דירוג שינה נמוך", "low-energy": "דירוג אנרגיה נמוך", "concern-mentioned": "צוינה דאגה בטקסט" } as const;
export default function CheckInsPanel({ clientId }: { clientId: string }) {
  const { checkIns, addCheckIn } = useClientData();
  const entries = useMemo(() => sortCheckIns(checkIns.filter((entry) => entry.clientId === clientId)), [checkIns, clientId]);
  const flags = getAttentionFlags(entries);
  const [form, setForm] = useState({ date: new Date().toISOString().slice(0, 10), weight: "", waist: "", hunger: "3", sleep: "3", energy: "3", training: true, note: "" });
  const [message, setMessage] = useState("");
  const valid = !!form.date && Number(form.weight) > 0 && Number(form.waist) > 0;
  function submit(event: React.FormEvent) { event.preventDefault(); if (!valid) { setMessage("יש להזין תאריך, משקל והיקף חיוביים."); return; } addCheckIn({ id: `check-${Date.now()}`, clientId, date: form.date, weightKg: Number(form.weight), waistCm: Number(form.waist), hunger: Number(form.hunger) as Rating, sleep: Number(form.sleep) as Rating, energy: Number(form.energy) as Rating, trainingCompleted: form.training, note: form.note.trim() || undefined }); setForm((current) => ({ ...current, weight: "", waist: "", note: "" })); setMessage("הצ׳ק-אין נוסף למצב הדמו של הסשן."); }
  return <div className="space-y-5">
    <section className="rounded-[24px] border border-[#E5E7E5] bg-[#FFFFFF] p-5"><h2 className="font-black">מצב נוכחי</h2><div className="mt-3 flex flex-wrap gap-2">{flags.length ? flags.map((flag) => <span key={flag} className="rounded-full border border-[#E5E7E5] bg-[#F7F8F7] px-3 py-1 text-xs text-[#0B0B0B]">{flagLabels[flag]}</span>) : <span className="rounded-full border border-[#16A34A]/30 bg-[#ECFDF3] px-3 py-1 text-xs text-[#16A34A]">אין דגלי תשומת לב ישירים</span>}</div><p className="mt-3 text-xs text-[#3F433F]">הדגלים מבוססים רק על עדכון חסר, דירוג 1–2 או מילות דאגה מפורשות; אין כאן פרשנות רפואית.</p></section>
    <section className="rounded-[26px] border border-[#E5E7E5] bg-[#FFFFFF] p-5"><h2 className="text-xl font-black">היסטוריית צ׳ק-אין</h2>{entries.length ? <div className="mt-4 space-y-3">{[...entries].reverse().map((entry, index) => <article key={entry.id} className="rounded-2xl bg-[#F7F8F7] p-4"><div className="flex flex-wrap justify-between gap-3"><div><strong>{index === 0 ? "העדכון האחרון" : entry.date}</strong><p className="text-xs text-[#5B5F5B]">{entry.date} · {entry.weightKg} ק״ג · {entry.waistCm} ס״מ</p></div><span className={entry.trainingCompleted ? "text-[#16A34A]" : "text-[#5B5F5B]"}>{entry.trainingCompleted ? "האימונים הושלמו" : "האימונים לא הושלמו"}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-center text-sm"><RatingBox label="רעב" value={entry.hunger}/><RatingBox label="שינה" value={entry.sleep}/><RatingBox label="אנרגיה" value={entry.energy}/></div>{entry.note && <p className="mt-3 text-sm text-[#3F433F]">{entry.note}</p>}</article>)}</div> : <p className="mt-4 rounded-2xl border border-dashed border-[#E5E7E5] p-10 text-center text-[#5B5F5B]">עדיין אין עדכונים שבועיים.</p>}</section>
    <form onSubmit={submit} className="rounded-[26px] border border-[#BBF7D0] bg-[#FFFFFF] p-5"><div className="flex items-center gap-2"><Plus className="text-[#16A34A]"/><h2 className="text-xl font-black">צ׳ק-אין שבועי לדמו</h2></div><p className="mt-1 text-xs text-[#5B5F5B]">הנתונים נשמרים בסשן בלבד. סולם הדירוג ניטרלי: 1–5.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Input label="תאריך" type="date" value={form.date} onChange={(date) => setForm({ ...form, date })}/><Input label="משקל (ק״ג)" type="number" value={form.weight} onChange={(weight) => setForm({ ...form, weight })}/><Input label="היקף מותניים (ס״מ)" type="number" value={form.waist} onChange={(waist) => setForm({ ...form, waist })}/>{(["hunger", "sleep", "energy"] as const).map((key) => <label key={key} className="text-sm text-[#3F433F]">{{ hunger: "רעב", sleep: "שינה", energy: "אנרגיה" }[key]} (1–5)<select className="nutrition-input mt-2" value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })}>{[1,2,3,4,5].map((value) => <option key={value}>{value}</option>)}</select></label>)}<label className="flex min-h-12 items-center gap-3 rounded-2xl border border-[#E5E7E5] px-4 text-sm"><input type="checkbox" checked={form.training} onChange={(event) => setForm({ ...form, training: event.target.checked })}/> האימונים המתוכננים הושלמו</label><label className="text-sm text-[#3F433F] sm:col-span-2">הערה חופשית<textarea className="nutrition-input mt-2" value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })}/></label></div>{message && <p aria-live="polite" className="mt-3 text-sm text-[#0B0B0B]">{message}</p>}<button disabled={!valid} className="mt-4 flex min-h-12 items-center gap-2 rounded-2xl bg-[#16A34A] px-5 font-black text-[#FFFFFF] disabled:opacity-40"><ClipboardCheck size={18}/>שמירת צ׳ק-אין</button></form>
  </div>;
}
function RatingBox({ label, value }: { label: string; value: number }) { return <div className="rounded-xl bg-[#F7F8F7] p-2"><span className="text-[#5B5F5B]">{label}</span><strong className="mr-2">{value}/5</strong></div>; }
function Input({ label, type, value, onChange }: { label: string; type: string; value: string; onChange: (value: string) => void }) { return <label className="text-sm text-[#3F433F]">{label}<input required className="nutrition-input mt-2" type={type} min={type === "number" ? "0.1" : undefined} step={type === "number" ? "0.1" : undefined} value={value} onChange={(event) => onChange(event.target.value)}/></label>; }
