"use client";
import { BellPlus, BookmarkPlus, Pencil, Send, Trash2 } from "lucide-react";
import { useState, useTransition } from "react";
import { createCoachNotification, deleteCoachClientNote, saveCoachClientNote, setClientContentAssignment } from "@/app/actions/coach";
type Content={id:string;title:string;assigned:boolean};type Notification={id:string;title:string;body:string;href:string;created_at:string;read_at:string|null};type Note={id:string;body:string;created_at:string;updated_at:string};
// These three join the same sectioned rhythm as the rest of the client card:
// stacked, collapsed, opened on purpose.
export default function ClientDetailExtras({clientId,content,notifications,notes}:{clientId:string;content:readonly Content[];notifications:readonly Notification[];notes:readonly Note[]}){return <div><ContentPanel clientId={clientId} content={content}/><NotificationsPanel clientId={clientId} notifications={notifications}/><NotesPanel clientId={clientId} notes={notes}/></div>}
function ContentPanel({clientId,content}:{clientId:string;content:readonly Content[]}){const[pending,start]=useTransition();const[message,setMessage]=useState("");return <Panel title="תוכן" description="שיוך תוכן אישי ללקוח"><div className="max-h-72 space-y-2 overflow-y-auto">{content.map(item=><div key={item.id} className="flex items-center justify-between gap-3 rounded-xl bg-[#F7F8F7] p-3 text-sm"><span>{item.title}</span><button disabled={pending} onClick={()=>start(async()=>setMessage((await setClientContentAssignment(clientId,item.id,!item.assigned)).message))} className="inline-flex min-h-9 items-center gap-1 rounded-lg border border-[#16A34A]/30 px-2 text-xs text-[#16A34A]"><BookmarkPlus size={14}/>{item.assigned?"הסרה":"שייך"}</button></div>)}{!content.length&&<Empty text="אין תוכן מפורסם לשיוך."/>}</div>{message&&<Status message={message}/>}</Panel>}
function NotificationsPanel({clientId,notifications}:{clientId:string;notifications:readonly Notification[]}){const[title,setTitle]=useState("");const[body,setBody]=useState("");const[href,setHref]=useState("/");const[pending,start]=useTransition();const[message,setMessage]=useState("");return <Panel title="התראות" description="שליחת התראה מיידית והיסטוריית קריאה"><div className="space-y-2"><Input label="כותרת" value={title} onChange={setTitle}/><Input label="תיאור" value={body} onChange={setBody}/><label className="text-xs font-bold">מעבר למסך<select className="nutrition-input mt-1" value={href} onChange={event=>setHref(event.target.value)}><option value="/">דשבורד</option><option value="/nutrition">תזונה</option><option value="/workouts">אימונים</option><option value="/check-in">צ׳ק־אין</option><option value="/progress">התקדמות</option><option value="/content">תוכן</option></select></label><button disabled={pending||!title.trim()} onClick={()=>start(async()=>{const result=await createCoachNotification(clientId,title,body,href);setMessage(result.message);if(result.ok){setTitle("");setBody("")}})} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-[#16A34A] px-3 text-sm font-black text-[#FFFFFF] disabled:opacity-50"><BellPlus size={16}/>שליחת התראה</button></div>{message&&<Status message={message}/>}<div className="mt-4 max-h-48 space-y-2 overflow-y-auto">{notifications.map(item=><p key={item.id} className="rounded-xl bg-[#F7F8F7] p-3 text-xs"><strong>{item.title}</strong><span className="mt-1 block text-[#5B5F5B]">{item.read_at?"נקראה":"לא נקראה"} · {new Date(item.created_at).toLocaleString("he-IL",{timeZone:"Asia/Jerusalem"})}</span></p>)}{!notifications.length&&<Empty text="אין התראות ללקוח."/>}</div></Panel>}
// Exported so the client file's "הערות מאמן" tab can show the notes on their own.
// Bundling them with content assignment and push notifications under that
// heading put two unrelated tools behind a label that promised one.
export function NotesPanel({clientId,notes,open=false}:{clientId:string;notes:readonly Note[];open?:boolean}){const[body,setBody]=useState("");const[editing,setEditing]=useState<string>();const[pending,start]=useTransition();const[message,setMessage]=useState("");const save=()=>start(async()=>{const result=await saveCoachClientNote(clientId,editing,body);setMessage(result.message);if(result.ok){setBody("");setEditing(undefined)}});return <Panel title="הערות מאמן" description="הערות פרטיות — אינן חשופות ללקוח" open={open}><textarea className="nutrition-input min-h-24" value={body} onChange={event=>setBody(event.target.value)} placeholder="הערה פרטית למעקב…"/><button disabled={pending||!body.trim()} onClick={save} className="mt-2 inline-flex min-h-10 items-center gap-2 rounded-xl bg-[#16A34A] px-3 text-sm font-black text-[#FFFFFF] disabled:opacity-50"><Send size={16}/>{editing?"עדכון הערה":"שמירת הערה"}</button>{message&&<Status message={message}/>}<div className="mt-4 max-h-48 space-y-2 overflow-y-auto">{notes.map(note=><article key={note.id} className="rounded-xl bg-[#F7F8F7] p-3 text-sm"><p>{note.body}</p><div className="mt-2 flex items-center gap-2 text-xs text-[#5B5F5B]"><span>{new Date(note.created_at).toLocaleString("he-IL",{timeZone:"Asia/Jerusalem"})}</span><button className="text-[#16A34A]" onClick={()=>{setEditing(note.id);setBody(note.body)}}><Pencil size={14}/><span className="sr-only">עריכה</span></button><button className="text-[#DC2626]" onClick={()=>{if(window.confirm("למחוק את ההערה?") )start(async()=>setMessage((await deleteCoachClientNote(clientId,note.id)).message))}}><Trash2 size={14}/><span className="sr-only">מחיקה</span></button></div></article>)}{!notes.length&&<Empty text="אין הערות פרטיות."/>}</div></Panel>}
function Panel({title,description,children,open=false}:{title:string;description:string;children:React.ReactNode;open?:boolean}){return <details className="disclosure" open={open}><summary><span className="min-w-0"><strong className="block">{title}</strong><span className="block truncate text-xs font-normal text-[#5B5F5B]">{description}</span></span></summary><div className="disclosure__body">{children}</div></details>};function Input({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="block text-xs font-bold">{label}<input className="nutrition-input mt-1" value={value} onChange={event=>onChange(event.target.value)}/></label>};function Empty({text}:{text:string}){return <p className="rounded-xl border border-dashed border-[#E5E7E5] p-3 text-center text-xs text-[#5B5F5B]">{text}</p>};function Status({message}:{message:string}){return <p role="status" className="mt-2 text-xs text-[#5B5F5B]">{message}</p>}
