"use client";
import { useEffect, useState, useTransition } from "react";
import { requestMagicLink, requestTestPasswordLogin, type LoginState } from "@/app/login/actions";
import { DEVICE_COOKIE } from "@/lib/auth/device";
const initial: LoginState = { status: "idle" };
export default function LoginForm({ testLoginEnabled = false, nextPath = "" }: { testLoginEnabled?: boolean; nextPath?: string }) {
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [testMode,setTestMode]=useState(false); const [state,setState]=useState<LoginState>(initial); const [pending,startTransition]=useTransition();
  useEffect(() => { let id = window.localStorage.getItem(DEVICE_COOKIE); if (!id) { id = crypto.randomUUID().replaceAll("-", ""); window.localStorage.setItem(DEVICE_COOKIE, id); } document.cookie = `${DEVICE_COOKIE}=${encodeURIComponent(id)}; Path=/; Max-Age=31536000; SameSite=Lax${location.protocol === "https:" ? "; Secure" : ""}`; }, []);
  function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setState(initial);const form=new FormData(event.currentTarget);startTransition(async()=>{const next=await (testMode?requestTestPasswordLogin:requestMagicLink)(initial,form);setState(next);if(testMode&&next.status==="sent"&&next.redirectTo)window.location.assign(next.redirectTo)})}
  return <form onSubmit={submit} className="mt-7 space-y-4"><input type="hidden" name="next" value={nextPath}/><label className="block text-sm font-bold text-[#3F433F]">אימייל<input name="email" value={email} onChange={(event)=>{setEmail(event.target.value);setState(initial)}} type="email" required autoComplete="email" className="nutrition-input mt-2" placeholder="name@example.com" dir="ltr"/></label>{testMode&&<label className="block text-sm font-bold text-[#3F433F]">סיסמת בדיקה<input name="password" value={password} onChange={(event)=>setPassword(event.target.value)} type="password" required autoComplete="current-password" className="nutrition-input mt-2"/></label>}{testLoginEnabled&&<label className="flex items-center gap-2 text-xs text-[#5B5F5B]"><input type="checkbox" checked={testMode} onChange={(e)=>{setTestMode(e.target.checked);setState(initial)}}/> כניסה לחשבון בדיקה</label>}{state.status!=="idle"&&state.message&&<p role={state.status === "error" ? "alert" : "status"} className={`rounded-2xl p-4 text-sm font-bold ${state.status==="error"?"bg-[#FEF2F2] text-[#DC2626]":"bg-[#ECFDF3] text-[#15803D]"}`}>{state.message}</p>}<button disabled={pending || state.status === "sent"} className="premium-primary-button w-full">{pending?"שולחים…":testMode?"כניסת בדיקה":"שליחת קישור התחברות"}</button></form>;
}
