begin;
create table public.food_favorites(user_id uuid not null references public.profiles(id) on delete cascade,food_id text not null references public.foods(id) on delete cascade,created_at timestamptz not null default now(),primary key(user_id,food_id));
alter table public.food_favorites enable row level security;
create policy food_favorites_self_select on public.food_favorites for select to authenticated using(user_id=auth.uid());
create policy food_favorites_self_insert on public.food_favorites for insert to authenticated with check(user_id=auth.uid());
create policy food_favorites_self_delete on public.food_favorites for delete to authenticated using(user_id=auth.uid());
revoke all on public.food_favorites from anon,authenticated;
grant select,insert,delete on public.food_favorites to authenticated;
notify pgrst,'reload schema';
commit;
