begin;

-- Reminders were pull-based: ensure_in_app_reminders and ensure_workout_day_reminders
-- both read auth.uid(), so they only ran when the client happened to open the
-- notifications page. Nothing fired while the app was closed, which is the opposite
-- of what a reminder is for.
--
-- This splits each rule into a _for_client(uuid) function holding the existing logic
-- unchanged, keeps the original zero-argument functions as thin wrappers so current
-- callers behave exactly as before, and adds a batch entry point a scheduler can call.
-- Notification text and dedupe keys are identical to the per-user path, so a reminder
-- generated by the scheduler and one generated by a page visit collapse into one row.

create or replace function public.ensure_in_app_reminders_for_client(p_client_id uuid) returns void
language plpgsql security definer set search_path = public as $$
declare v_week text := to_char(current_date, 'IYYY-IW');
begin
  if p_client_id is null or not public.notification_enabled(p_client_id, 'reminders') then return; end if;
  if not exists(select 1 from public.check_ins where client_id = p_client_id and submitted_at >= now() - interval '7 days') then
    perform public.create_in_app_notification(p_client_id, null, 'reminders', 'check_in_reminder', 'תזכורת לצ׳ק-אין', 'הגיע הזמן לעדכן איך עבר עליך השבוע.', '/check-in', 'reminders', v_week, 'check-in-reminder-' || v_week);
  end if;
  if not exists(select 1 from public.progress_entries where client_id = p_client_id and date >= current_date - 7) then
    perform public.create_in_app_notification(p_client_id, null, 'reminders', 'weight_reminder', 'תזכורת להזנת משקל', 'מדידה עדכנית עוזרת למעקב ולתוכנית שלך.', '/progress', 'reminders', v_week, 'weight-reminder-' || v_week);
  end if;
end $$;

create or replace function public.ensure_workout_day_reminders_for_client(p_client_id uuid) returns void
language plpgsql security definer set search_path = public as $$
declare
  v_now timestamp := timezone('Asia/Jerusalem', now());
  v_today date := v_now::date;
  v_time time := v_now::time;
  v_assignment public.workout_assignments%rowtype;
  v_morning_enabled boolean := true;
  v_evening_enabled boolean := true;
  v_morning_time time := time '08:00';
  v_evening_time time := time '19:30';
begin
  if p_client_id is null or not public.notification_enabled(p_client_id, 'reminders') or not public.notification_enabled(p_client_id, 'workouts') then return; end if;
  select * into v_assignment from public.workout_assignments where client_id = p_client_id and status = 'active' and start_date <= v_today and (end_date is null or end_date >= v_today) limit 1;
  if not found or not public.workout_is_planned_on(v_assignment, v_today) then return; end if;
  if exists(select 1 from public.workout_sessions where client_id = p_client_id and assignment_id = v_assignment.id and status = 'completed' and (completed_at at time zone 'Asia/Jerusalem')::date = v_today) then return; end if;
  select workout_morning_reminder, workout_evening_reminder, workout_morning_reminder_time, workout_evening_reminder_time
    into v_morning_enabled, v_evening_enabled, v_morning_time, v_evening_time
  from public.notification_preferences where user_id = p_client_id;
  if v_morning_enabled and v_time >= v_morning_time and v_time < v_evening_time then
    perform public.create_in_app_notification(p_client_id, null, 'reminders', 'workout_morning_reminder', 'יש לך אימון היום 💪', 'האימון שלך מחכה לך. תכנן מתי אתה עושה אותו היום.', '/workouts', 'workout_assignments', v_assignment.id::text, 'workout-morning-' || v_assignment.id::text || '-' || v_today::text);
  end if;
  if v_evening_enabled and v_time >= v_evening_time then
    perform public.create_in_app_notification(p_client_id, null, 'reminders', 'workout_evening_reminder', 'עוד לא סימנת את האימון של היום', 'נשאר לך לסגור את האימון לפני שהיום נגמר.', '/workouts', 'workout_assignments', v_assignment.id::text, 'workout-evening-' || v_assignment.id::text || '-' || v_today::text);
  end if;
end $$;

-- Batch entry point for the scheduler. Runs the check-in, weight and workout rules
-- for every active client and
-- returns how many were processed. A failure for one client is logged and skipped so
-- one bad row cannot stop the whole run.
create or replace function public.run_scheduled_reminders() returns integer
language plpgsql security definer set search_path = public as $$
declare v_client record; v_count integer := 0;
begin
  for v_client in
    select p.id from public.profiles p
      join public.user_roles r on r.user_id = p.id and r.role = 'client'
     where p.status = 'active'
  loop
    begin
      perform public.ensure_in_app_reminders_for_client(v_client.id);
      perform public.ensure_workout_day_reminders_for_client(v_client.id);
      v_count := v_count + 1;
    exception when others then
      raise warning 'reminder generation failed for %: %', v_client.id, sqlerrm;
    end;
  end loop;
  return v_count;
end $$;

-- The originals become wrappers so nothing that calls them today changes behaviour.
create or replace function public.ensure_in_app_reminders() returns void
language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null or public.current_role() <> 'client' then return; end if;
  perform public.ensure_in_app_reminders_for_client(auth.uid());
end $$;

create or replace function public.ensure_workout_day_reminders() returns void
language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null or public.current_role() <> 'client' then return; end if;
  perform public.ensure_workout_day_reminders_for_client(auth.uid());
end $$;

-- Only the service role may run the batch or reach another client's generator.
revoke all on function
  public.ensure_in_app_reminders_for_client(uuid),
  public.ensure_workout_day_reminders_for_client(uuid),
  public.run_scheduled_reminders()
from public, anon, authenticated;

grant execute on function public.ensure_in_app_reminders(), public.ensure_workout_day_reminders() to authenticated;
grant execute on function public.run_scheduled_reminders() to service_role;

notify pgrst, 'reload schema';
commit;
