begin;

create table public.client_events (
 id uuid primary key default gen_random_uuid(), client_id uuid not null references public.profiles(id) on delete cascade, actor_id uuid references public.profiles(id) on delete set null, event_type text not null check(event_type in ('meal_marked','workout_completed','workout_skipped','workout_moved','weight_updated','check_in_submitted','client_login','nutrition_target_changed')), entity_type text, entity_id text, occurred_at timestamptz not null default now(), metadata jsonb not null default '{}'::jsonb
);
create index client_events_client_time_idx on public.client_events(client_id,occurred_at desc);

create table public.habit_analysis_reports (
 id uuid primary key default gen_random_uuid(), client_id uuid not null references public.profiles(id) on delete cascade, coach_id uuid not null references public.profiles(id) on delete cascade, week_start date not null, week_end date not null, consistency_score smallint not null check(consistency_score between 0 and 100), nutrition_score smallint not null check(nutrition_score between 0 and 100), workout_score smallint not null check(workout_score between 0 and 100), tracking_score smallint not null check(tracking_score between 0 and 100), client_health_score smallint not null check(client_health_score between 0 and 100), risk_score smallint not null check(risk_score between 0 and 100), retention_risk smallint not null check(retention_risk between 0 and 100), summary text not null, progress_explanation text not null, strengths jsonb not null default '[]'::jsonb, improvements jsonb not null default '[]'::jsonb, recommended_actions jsonb not null default '[]'::jsonb, metrics jsonb not null default '{}'::jsonb, status text not null default 'ready' check(status in ('ready','insufficient_data')), created_at timestamptz not null default now(), unique(client_id,week_start,week_end)
);
create index habit_reports_coach_week_idx on public.habit_analysis_reports(coach_id,week_end desc);

create table public.free_menu_days (id uuid primary key default gen_random_uuid(), client_id uuid not null references public.profiles(id) on delete cascade, coach_id uuid references public.profiles(id) on delete set null, menu_date date not null, calorie_target numeric(10,2), protein_target numeric(10,2), allow_manual boolean not null default true, status text not null default 'active' check(status in ('active','closed')), created_at timestamptz not null default now(), unique(client_id,menu_date));
create table public.free_menu_entries (id uuid primary key default gen_random_uuid(), free_menu_day_id uuid not null references public.free_menu_days(id) on delete cascade, food_id text references public.foods(id) on delete set null, name text not null, quantity numeric(10,2) not null check(quantity>0), unit text not null default 'g', meal_label text not null default 'חופשי', eaten_at timestamptz not null default now(), notes text, calories numeric(10,2), protein numeric(10,2), carbohydrates numeric(10,2), fat numeric(10,2), has_nutrition boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index free_menu_entries_day_idx on public.free_menu_entries(free_menu_day_id,eaten_at);
create table public.free_menu_daily_summaries (id uuid primary key default gen_random_uuid(), free_menu_day_id uuid not null unique references public.free_menu_days(id) on delete cascade, calories numeric(12,2) not null default 0, protein numeric(12,2) not null default 0, carbohydrates numeric(12,2) not null default 0, fat numeric(12,2) not null default 0, entries_count integer not null default 0, missing_nutrition_count integer not null default 0, updated_at timestamptz not null default now());

alter table public.client_events enable row level security; alter table public.habit_analysis_reports enable row level security; alter table public.free_menu_days enable row level security; alter table public.free_menu_entries enable row level security; alter table public.free_menu_daily_summaries enable row level security;
create policy events_participant_read on public.client_events for select to authenticated using(client_id=auth.uid() or public.is_coach_for(client_id));
create policy reports_participant_read on public.habit_analysis_reports for select to authenticated using(client_id=auth.uid() or coach_id=auth.uid());
create policy free_days_participant_read on public.free_menu_days for select to authenticated using(client_id=auth.uid() or public.is_coach_for(client_id));
create policy free_entries_participant_read on public.free_menu_entries for select to authenticated using(exists(select 1 from public.free_menu_days d where d.id=free_menu_day_id and (d.client_id=auth.uid() or public.is_coach_for(d.client_id))));
create policy free_summaries_participant_read on public.free_menu_daily_summaries for select to authenticated using(exists(select 1 from public.free_menu_days d where d.id=free_menu_day_id and (d.client_id=auth.uid() or public.is_coach_for(d.client_id))));
revoke all on public.client_events,public.habit_analysis_reports,public.free_menu_days,public.free_menu_entries,public.free_menu_daily_summaries from anon,authenticated; grant select on public.client_events,public.habit_analysis_reports,public.free_menu_days,public.free_menu_entries,public.free_menu_daily_summaries to authenticated;

create or replace function public.log_client_event(p_event_type text,p_entity_type text default null,p_entity_id text default null,p_metadata jsonb default '{}'::jsonb) returns void language plpgsql security invoker set search_path=public as $$ begin if auth.uid() is null then raise exception 'not_authenticated'; end if; insert into public.client_events(client_id,actor_id,event_type,entity_type,entity_id,metadata) values(auth.uid(),auth.uid(),p_event_type,p_entity_type,p_entity_id,coalesce(p_metadata,'{}')); end $$;
create or replace function public.save_free_menu_entry(p_date date,p_food_id text,p_name text,p_quantity numeric,p_unit text,p_meal_label text,p_eaten_at timestamptz,p_notes text,p_calories numeric,p_protein numeric,p_carbohydrates numeric,p_fat numeric,p_has_nutrition boolean) returns uuid language plpgsql security definer set search_path=public as $$ declare v_day uuid; v_entry uuid; begin if public.current_role()<>'client' or p_date<current_date then raise exception 'invalid_free_menu_date'; end if; insert into public.free_menu_days(client_id,menu_date) values(auth.uid(),p_date) on conflict(client_id,menu_date) do update set client_id=excluded.client_id returning id into v_day; insert into public.free_menu_entries(free_menu_day_id,food_id,name,quantity,unit,meal_label,eaten_at,notes,calories,protein,carbohydrates,fat,has_nutrition) values(v_day,nullif(p_food_id,''),p_name,p_quantity,coalesce(nullif(p_unit,''),'g'),coalesce(nullif(p_meal_label,''),'חופשי'),coalesce(p_eaten_at,now()),nullif(p_notes,''),p_calories,p_protein,p_carbohydrates,p_fat,p_has_nutrition) returning id into v_entry; insert into public.free_menu_daily_summaries(free_menu_day_id,calories,protein,carbohydrates,fat,entries_count,missing_nutrition_count) select v_day,coalesce(sum(case when has_nutrition then calories else 0 end),0),coalesce(sum(case when has_nutrition then protein else 0 end),0),coalesce(sum(case when has_nutrition then carbohydrates else 0 end),0),coalesce(sum(case when has_nutrition then fat else 0 end),0),count(*),count(*) filter(where not has_nutrition) from public.free_menu_entries where free_menu_day_id=v_day on conflict(free_menu_day_id) do update set calories=excluded.calories,protein=excluded.protein,carbohydrates=excluded.carbohydrates,fat=excluded.fat,entries_count=excluded.entries_count,missing_nutrition_count=excluded.missing_nutrition_count,updated_at=now(); return v_entry; end $$;
revoke all on function public.log_client_event(text,text,text,jsonb),public.save_free_menu_entry(date,text,text,numeric,text,text,timestamptz,text,numeric,numeric,numeric,numeric,boolean) from public; grant execute on function public.log_client_event(text,text,text,jsonb),public.save_free_menu_entry(date,text,text,numeric,text,text,timestamptz,text,numeric,numeric,numeric,numeric,boolean) to authenticated;
notify pgrst,'reload schema'; commit;
