-- KFC, חנוכה, אוכל רחוב and דומינוס from fuder.co.il; generated by
-- scripts/generate-fuder-restaurant-migration.mjs, one transaction per category.

begin;

insert into public.foods (
  id, name, brand, category, calories, protein, carbs, fat,
  package_quantity, package_unit, serving_label, verification_status, notes,
  source_url, unit_weight_grams, calories_per_unit, units_per_package
) values
  ('657', 'ג''וניור בורגר KFC (110 גרם)', 'KFC', 'KFC', 288.182, 10.909, 25.455, 10.909, 1, 'יחידה', 'יחידה (110 גרם)', 'מאושר', 'לפי Fuder, יחידה (110 גרם): 317 קלוריות, 12.1 גרם חלבון, 27.5 גרם פחמימות, 12.1 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%92%d7%95%d7%a0%d7%99%d7%95%d7%a8-%d7%91%d7%95%d7%a8%d7%92%d7%a8-kfc/', 110, 317, 1),
  ('658', 'גראנד קריספי בורגר KFC (310 גרם)', 'KFC', 'KFC', 211.935, 11.935, 25.161, 7.097, 1, 'יחידה', 'יחידה (310 גרם)', 'מאושר', 'לפי Fuder, יחידה (310 גרם): 657 קלוריות, 37.2 גרם חלבון, 77.5 גרם פחמימות, 21.7 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%92%d7%a8%d7%90%d7%a0%d7%93-%d7%a7%d7%a8%d7%99%d7%a1%d7%a4%d7%99-%d7%91%d7%95%d7%a8%d7%92%d7%a8-kfc/', 310, 657, 1),
  ('659', 'דאבל טאוור זינגר בורגר KFC (430 גרם)', 'KFC', 'KFC', 237.907, 12.093, 13.953, 15.116, 1, 'יחידה', 'יחידה (430 גרם)', 'מאושר', 'לפי Fuder, יחידה (430 גרם): 1023 קלוריות, 51.6 גרם חלבון, 60.2 גרם פחמימות, 64.5 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%93%d7%90%d7%91%d7%9c-%d7%98%d7%90%d7%95%d7%95%d7%a8-%d7%96%d7%99%d7%a0%d7%92%d7%a8-%d7%91%d7%95%d7%a8%d7%92%d7%a8-kfc/', 430, 1023, 1),
  ('660', 'דאבל קלאסיק טאוור בורגר KFC (435 גרם)', 'KFC', 'KFC', 245.057, 13.103, 17.931, 14.023, 1, 'יחידה', 'יחידה (435 גרם)', 'מאושר', 'לפי Fuder, יחידה (435 גרם): 1066 קלוריות, 56.6 גרם חלבון, 78.3 גרם פחמימות, 60.9 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%93%d7%90%d7%91%d7%9c-%d7%a7%d7%9c%d7%90%d7%a1%d7%99%d7%a7-%d7%98%d7%90%d7%95%d7%95%d7%a8-%d7%91%d7%95%d7%a8%d7%92%d7%a8-kfc/', 435, 1066, 1),
  ('661', 'זינגר בורגר KFC (175 גרם)', 'KFC', 'KFC', 308, 17.143, 18.857, 18.286, 1, 'יחידה', 'יחידה (175 גרם)', 'מאושר', 'לפי Fuder, יחידה (175 גרם): 539 קלוריות, 29.8 גרם חלבון, 33.3 גרם פחמימות, 31.5 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%96%d7%99%d7%a0%d7%92%d7%a8-%d7%91%d7%95%d7%a8%d7%92%d7%a8-kfc/', 175, 539, 1),
  ('662', 'טאוור זינגר בורגר KFC (255 גרם)', 'KFC', 'KFC', 294.902, 12.941, 25.882, 21.961, 1, 'יחידה', 'יחידה (255 גרם)', 'מאושר', 'לפי Fuder, יחידה (255 גרם): 752 קלוריות, 33.2 גרם חלבון, 66.3 גרם פחמימות, 56.1 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%98%d7%90%d7%95%d7%95%d7%a8-%d7%96%d7%99%d7%a0%d7%92%d7%a8-%d7%91%d7%95%d7%a8%d7%92%d7%a8-kfc/', 255, 752, 1),
  ('663', 'טורטיה אייטוויסטר חריף KFC (110 גרם)', 'KFC', 'KFC', 256.364, 11.818, 22.727, 13.636, 1, 'יחידה', 'יחידה (110 גרם)', 'מאושר', 'לפי Fuder, יחידה (110 גרם): 282 קלוריות, 13.2 גרם חלבון, 25.3 גרם פחמימות, 15.4 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%98%d7%95%d7%a8%d7%98%d7%99%d7%94-%d7%90%d7%99%d7%99%d7%98%d7%95%d7%95%d7%99%d7%a1%d7%98%d7%a8-%d7%97%d7%a8%d7%99%d7%a3-kfc/', 110, 282, 1),
  ('664', 'טורטיה אייטוויסטר KFC (113 גרם)', 'KFC', 'KFC', 255.752, 12.389, 23.009, 13.274, 1, 'יחידה', 'יחידה (113 גרם)', 'מאושר', 'לפי Fuder, יחידה (112.5 גרם): 289 קלוריות, 13.5 גרם חלבון, 25.9 גרם פחמימות, 14.6 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%98%d7%95%d7%a8%d7%98%d7%99%d7%94-%d7%90%d7%99%d7%99%d7%98%d7%95%d7%95%d7%99%d7%a1%d7%98%d7%a8-kfc/', 113, 289, 1),
  ('665', 'טורטיה בוקס מאסטר חריף KFC (215 גרם)', 'KFC', 'KFC', 377.209, 12.093, 21.86, 25.116, 1, 'יחידה', 'יחידה (215 גרם)', 'מאושר', 'לפי Fuder, יחידה (215 גרם): 811 קלוריות, 25.8 גרם חלבון, 47.3 גרם פחמימות, 53.8 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%98%d7%95%d7%a8%d7%98%d7%99%d7%94-%d7%91%d7%95%d7%a7%d7%a1-%d7%9e%d7%90%d7%a1%d7%98%d7%a8-%d7%97%d7%a8%d7%99%d7%a3-kfc/', 215, 811, 1),
  ('666', 'טורטיה בוקס מאסטר KFC (210 גרם)', 'KFC', 'KFC', 390, 13.81, 22.857, 27.143, 1, 'יחידה', 'יחידה (210 גרם)', 'מאושר', 'לפי Fuder, יחידה (210 גרם): 819 קלוריות, 29.4 גרם חלבון, 48.3 גרם פחמימות, 56.7 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%98%d7%95%d7%a8%d7%98%d7%99%d7%94-%d7%91%d7%95%d7%a7%d7%a1-%d7%9e%d7%90%d7%a1%d7%98%d7%a8-kfc/', 210, 819, 1),
  ('667', 'טורטיה טוויסטר חריף KFC (211 גרם)', 'KFC', 'KFC', 245.972, 10.9, 19.905, 14.218, 1, 'יחידה', 'יחידה (211 גרם)', 'מאושר', 'לפי Fuder, יחידה (211 גרם): 519 קלוריות, 23.2 גרם חלבון, 42.2 גרם פחמימות, 29.5 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%98%d7%95%d7%a8%d7%98%d7%99%d7%94-%d7%98%d7%95%d7%95%d7%99%d7%a1%d7%98%d7%a8-%d7%97%d7%a8%d7%99%d7%a3-kfc/', 211, 519, 1),
  ('668', 'טורטיה טוויסטר KFC (211 גרם)', 'KFC', 'KFC', 245.972, 11.848, 19.905, 12.796, 1, 'יחידה', 'יחידה (211 גרם)', 'מאושר', 'לפי Fuder, יחידה (211 גרם): 519 קלוריות, 25.3 גרם חלבון, 42.2 גרם פחמימות, 27.4 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%98%d7%95%d7%a8%d7%98%d7%99%d7%94-%d7%98%d7%95%d7%95%d7%99%d7%a1%d7%98%d7%a8-kfc/', 211, 519, 1),
  ('669', 'מיני בורגר KFC (170 גרם)', 'KFC', 'KFC', 260, 15.294, 24.118, 11.765, 1, 'יחידה', 'יחידה (170 גרם)', 'מאושר', 'לפי Fuder, יחידה (170 גרם): 442 קלוריות, 25.5 גרם חלבון, 40.8 גרם פחמימות, 20.4 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%9e%d7%99%d7%a0%d7%99-%d7%91%d7%95%d7%a8%d7%92%d7%a8-kfc/', 170, 442, 1),
  ('670', 'סטריפס עוף חריף KFC (42 גרם)', 'KFC', 'KFC', 214.286, 23.81, 11.905, 9.524, 1, 'יחידה', 'יחידה (42 גרם)', 'מאושר', 'לפי Fuder, יחידה (42 גרם): 90 קלוריות, 9.7 גרם חלבון, 5 גרם פחמימות, 3.8 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a1%d7%98%d7%a8%d7%99%d7%a4%d7%a1-%d7%a2%d7%95%d7%a3-%d7%97%d7%a8%d7%99%d7%a3-kfc/', 42, 90, 1),
  ('671', 'סטריפס עוף רגיל KFC (42 גרם)', 'KFC', 'KFC', 214.286, 23.81, 11.905, 9.524, 1, 'יחידה', 'יחידה (42 גרם)', 'מאושר', 'לפי Fuder, יחידה (42 גרם): 90 קלוריות, 9.7 גרם חלבון, 5 גרם פחמימות, 3.8 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a1%d7%98%d7%a8%d7%99%d7%a4%d7%a1-%d7%a2%d7%95%d7%a3-%d7%a8%d7%92%d7%99%d7%9c-kfc/', 42, 90, 1),
  ('672', 'עוף על העצם KFC (115 גרם)', 'KFC', 'KFC', 260.87, 23.478, 11.304, 13.913, 1, 'יחידה', 'יחידה (115 גרם)', 'מאושר', 'לפי Fuder, יחידה (115 גרם): 300 קלוריות, 26.5 גרם חלבון, 12.6 גרם פחמימות, 16.1 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a2%d7%95%d7%a3-%d7%a2%d7%9c-%d7%94%d7%a2%d7%a6%d7%9d-kfc/', 115, 300, 1),
  ('673', 'קלאסיק בורגר KFC (187 גרם)', 'KFC', 'KFC', 271.123, 14.973, 19.786, 13.904, 1, 'יחידה', 'יחידה (187 גרם)', 'מאושר', 'לפי Fuder, יחידה (187 גרם): 507 קלוריות, 28.1 גרם חלבון, 37.4 גרם פחמימות, 26.2 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a7%d7%9c%d7%90%d7%a1%d7%99%d7%a7-%d7%91%d7%95%d7%a8%d7%92%d7%a8-kfc/', 187, 507, 1),
  ('674', 'קלאסיק טאוור בורגר KFC (255 גרם)', 'KFC', 'KFC', 292.157, 12.157, 18.039, 18.824, 1, 'יחידה', 'יחידה (255 גרם)', 'מאושר', 'לפי Fuder, יחידה (255 גרם): 745 קלוריות, 30.6 גרם חלבון, 45.9 גרם פחמימות, 48.4 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a7%d7%9c%d7%90%d7%a1%d7%99%d7%a7-%d7%98%d7%90%d7%95%d7%95%d7%a8-%d7%91%d7%95%d7%a8%d7%92%d7%a8-kfc/', 255, 745, 1)
on conflict (id) do update set
  name = excluded.name,
  brand = excluded.brand,
  category = excluded.category,
  calories = excluded.calories,
  protein = excluded.protein,
  carbs = excluded.carbs,
  fat = excluded.fat,
  package_quantity = excluded.package_quantity,
  package_unit = excluded.package_unit,
  serving_label = excluded.serving_label,
  verification_status = excluded.verification_status,
  notes = excluded.notes,
  source_url = excluded.source_url,
  unit_weight_grams = excluded.unit_weight_grams,
  calories_per_unit = excluded.calories_per_unit,
  units_per_package = excluded.units_per_package,
  updated_at = now();

do $$
begin
  if (select count(*) from public.foods where category = 'KFC') <> 18 then
    raise exception 'fuder_restaurant_upsert_failed';
  end if;
end $$;

commit;

begin;

insert into public.foods (
  id, name, brand, category, calories, protein, carbs, fat,
  package_quantity, package_unit, serving_label, verification_status, notes,
  source_url, unit_weight_grams, calories_per_unit, units_per_package
) values
  ('675', 'לביבות תפוחי אדמה מטוגנות (110 גרם)', null, 'חנוכה', 140, 2.727, 18.182, 6.364, 1, 'יחידה', 'יחידה (110 גרם)', 'מאושר', 'לפי Fuder, יחידה (110 גרם): 154 קלוריות, 2.8 גרם חלבון, 19.8 גרם פחמימות, 6.6 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%9c%d7%91%d7%99%d7%91%d7%95%d7%aa-%d7%aa%d7%a4%d7%95%d7%97%d7%99-%d7%90%d7%93%d7%9e%d7%94-%d7%9e%d7%98%d7%95%d7%92%d7%a0%d7%95%d7%aa/', 110, 154, 1),
  ('676', 'סופגנייה במילוי פיסטוק קסיס (90 גרם)', null, 'חנוכה', 408.889, 5.556, 40, 25.556, 1, 'יחידה', 'יחידה (90 גרם)', 'מאושר', 'לפי Fuder, יחידה (90 גרם): 368 קלוריות, 5.4 גרם חלבון, 36 גרם פחמימות, 22.5 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a1%d7%95%d7%a4%d7%92%d7%a0%d7%99%d7%99%d7%94-%d7%91%d7%9e%d7%99%d7%9c%d7%95%d7%99-%d7%a4%d7%99%d7%a1%d7%98%d7%95%d7%a7-%d7%a7%d7%a1%d7%99%d7%a1/', 90, 368, 1),
  ('677', 'סופגנייה במילוי פיסטוק קסיס קטנה (52 גרם)', null, 'חנוכה', 409.615, 5.769, 40.385, 25, 1, 'יחידה', 'יחידה (52 גרם)', 'מאושר', 'לפי Fuder, יחידה קטנה (52 גרם): 213 קלוריות, 3.1 גרם חלבון, 20.8 גרם פחמימות, 13 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a1%d7%95%d7%a4%d7%92%d7%a0%d7%99%d7%99%d7%94-%d7%91%d7%9e%d7%99%d7%9c%d7%95%d7%99-%d7%a4%d7%99%d7%a1%d7%98%d7%95%d7%a7-%d7%a7%d7%a1%d7%99%d7%a1/', 52, 213, 1),
  ('678', 'סופגנייה במילוי קרם ושוקולד לבן (90 גרם)', null, 'חנוכה', 395.556, 5.556, 42.222, 23.333, 1, 'יחידה', 'יחידה (90 גרם)', 'מאושר', 'לפי Fuder, יחידה (90 גרם): 356 קלוריות, 4.5 גרם חלבון, 37.8 גרם פחמימות, 20.7 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a1%d7%95%d7%a4%d7%92%d7%a0%d7%99%d7%99%d7%94-%d7%91%d7%9e%d7%99%d7%9c%d7%95%d7%99-%d7%a7%d7%a8%d7%9d-%d7%95%d7%a9%d7%95%d7%a7%d7%95%d7%9c%d7%93-%d7%9c%d7%91%d7%9f/', 90, 356, 1),
  ('679', 'סופגנייה במילוי קרם ושוקולד לבן קטנה (52 גרם)', null, 'חנוכה', 394.231, 5.769, 42.308, 23.077, 1, 'יחידה', 'יחידה (52 גרם)', 'מאושר', 'לפי Fuder, יחידה קטנה (52 גרם): 205 קלוריות, 2.6 גרם חלבון, 21.8 גרם פחמימות, 12 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a1%d7%95%d7%a4%d7%92%d7%a0%d7%99%d7%99%d7%94-%d7%91%d7%9e%d7%99%d7%9c%d7%95%d7%99-%d7%a7%d7%a8%d7%9d-%d7%95%d7%a9%d7%95%d7%a7%d7%95%d7%9c%d7%93-%d7%9c%d7%91%d7%9f/', 52, 205, 1),
  ('680', 'סופגנייה עם ריבה (90 גרם)', null, 'חנוכה', 375.556, 4.444, 46.667, 18.889, 1, 'יחידה', 'יחידה (90 גרם)', 'מאושר', 'לפי Fuder, יחידה (90 גרם): 338 קלוריות, 3.6 גרם חלבון, 42.3 גרם פחמימות, 17.1 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a1%d7%95%d7%a4%d7%92%d7%a0%d7%99%d7%99%d7%94-%d7%a2%d7%9d-%d7%a8%d7%99%d7%91%d7%94/', 90, 338, 1),
  ('681', 'סופגנייה עם ריבה (150 גרם)', null, 'חנוכה', 375.333, 4, 47.333, 19.333, 1, 'יחידה', 'יחידה (150 גרם)', 'מאושר', 'לפי Fuder, יחידה (150 גרם): 563 קלוריות, 6 גרם חלבון, 70.5 גרם פחמימות, 28.5 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a1%d7%95%d7%a4%d7%92%d7%a0%d7%99%d7%99%d7%94-%d7%a2%d7%9d-%d7%a8%d7%99%d7%91%d7%94/', 150, 563, 1),
  ('682', 'ספינג'' מרוקאי (75 גרם)', null, 'חנוכה', 294.667, 5.333, 44, 10.667, 1, 'יחידה', 'יחידה (75 גרם)', 'מאושר', 'לפי Fuder, יחידה (75 גרם): 221 קלוריות, 3.8 גרם חלבון, 33 גרם פחמימות, 8.3 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a1%d7%a4%d7%99%d7%a0%d7%92-%d7%9e%d7%a8%d7%95%d7%a7%d7%90%d7%99/', 75, 221, 1),
  ('683', 'קוגל – קיגל (66 גרם)', null, 'חנוכה', 200, 4.545, 33.333, 6.061, 1, 'מנה', 'מנה (66 גרם)', 'מאושר', 'לפי Fuder, מנה (66 גרם): 132 קלוריות, 2.6 גרם חלבון, 22.4 גרם פחמימות, 3.5 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a7%d7%95%d7%92%d7%9c-%d7%a7%d7%99%d7%92%d7%9c/', 66, 132, 1),
  ('684', 'רוזלך – רוגלך (38 גרם)', null, 'חנוכה', 357.895, 5.263, 55.263, 13.158, 1, 'יחידה', 'יחידה (38 גרם)', 'מאושר', 'לפי Fuder, יחידה (38 גרם): 136 קלוריות, 2.3 גרם חלבון, 20.5 גרם פחמימות, 4.9 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a8%d7%95%d7%96%d7%9c%d7%9a-%d7%a8%d7%95%d7%92%d7%9c%d7%9a/', 38, 136, 1)
on conflict (id) do update set
  name = excluded.name,
  brand = excluded.brand,
  category = excluded.category,
  calories = excluded.calories,
  protein = excluded.protein,
  carbs = excluded.carbs,
  fat = excluded.fat,
  package_quantity = excluded.package_quantity,
  package_unit = excluded.package_unit,
  serving_label = excluded.serving_label,
  verification_status = excluded.verification_status,
  notes = excluded.notes,
  source_url = excluded.source_url,
  unit_weight_grams = excluded.unit_weight_grams,
  calories_per_unit = excluded.calories_per_unit,
  units_per_package = excluded.units_per_package,
  updated_at = now();

do $$
begin
  if (select count(*) from public.foods where category = 'חנוכה') <> 10 then
    raise exception 'fuder_restaurant_upsert_failed';
  end if;
end $$;

commit;

begin;

insert into public.foods (
  id, name, brand, category, calories, protein, carbs, fat,
  package_quantity, package_unit, serving_label, verification_status, notes,
  source_url, unit_weight_grams, calories_per_unit, units_per_package
) values
  ('685', 'פלאפל בפיתה (מנה)', null, 'אוכל רחוב', 683, 30, 81, 33, 1, 'מנה', 'מנה', 'מאושר', 'לפי Fuder, מנה: 683 קלוריות, 29.7 גרם חלבון, 81.2 גרם פחמימות, 32.7 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a4%d7%9c%d7%a4%d7%9c-%d7%91%d7%a4%d7%99%d7%aa%d7%94/', 100, 683, 1),
  ('686', 'שווארמה בלאפה (מנה)', null, 'אוכל רחוב', 1158, 43, 240, 139, 1, 'מנה', 'מנה', 'מאושר', 'לפי Fuder, מנה: 1158 קלוריות, 42.6 גרם חלבון, 239.6 גרם פחמימות, 138.6 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a9%d7%95%d7%95%d7%90%d7%a8%d7%9e%d7%94-%d7%91%d7%9c%d7%90%d7%a4%d7%94/', 100, 1158, 1),
  ('687', 'שווארמה בפיתה (מנה)', null, 'אוכל רחוב', 817, 30, 169, 98, 1, 'מנה', 'מנה', 'מאושר', 'לפי Fuder, מנה: 817 קלוריות, 29.7 גרם חלבון, 169.3 גרם פחמימות, 98 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a9%d7%95%d7%95%d7%90%d7%a8%d7%9e%d7%94-%d7%91%d7%a4%d7%99%d7%aa%d7%94/', 100, 817, 1),
  ('688', 'שווארמה בצלחת (מנה)', null, 'אוכל רחוב', 502, 42, 3, 25, 1, 'מנה', 'מנה', 'מאושר', 'לפי Fuder, מנה: 502 קלוריות, 41.6 גרם חלבון, 3 גרם פחמימות, 24.8 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a9%d7%95%d7%95%d7%90%d7%a8%d7%9e%d7%94-%d7%91%d7%a6%d7%9c%d7%97%d7%aa/', 100, 502, 1)
on conflict (id) do update set
  name = excluded.name,
  brand = excluded.brand,
  category = excluded.category,
  calories = excluded.calories,
  protein = excluded.protein,
  carbs = excluded.carbs,
  fat = excluded.fat,
  package_quantity = excluded.package_quantity,
  package_unit = excluded.package_unit,
  serving_label = excluded.serving_label,
  verification_status = excluded.verification_status,
  notes = excluded.notes,
  source_url = excluded.source_url,
  unit_weight_grams = excluded.unit_weight_grams,
  calories_per_unit = excluded.calories_per_unit,
  units_per_package = excluded.units_per_package,
  updated_at = now();

do $$
begin
  if (select count(*) from public.foods where category = 'אוכל רחוב') <> 4 then
    raise exception 'fuder_restaurant_upsert_failed';
  end if;
end $$;

commit;

begin;

insert into public.foods (
  id, name, brand, category, calories, protein, carbs, fat,
  package_quantity, package_unit, serving_label, verification_status, notes,
  source_url, unit_weight_grams, calories_per_unit, units_per_package
) values
  ('689', 'לחם שום דומינוס (170 גרם)', 'דומינוס', 'דומינוס', 311.765, 7.059, 41.765, 12.353, 1, 'מנה', 'מנה (170 גרם)', 'מאושר', 'לפי Fuder, מנה (170 גרם): 530 קלוריות, 12.1 גרם חלבון, 71.4 גרם פחמימות, 21.3 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%9c%d7%97%d7%9d-%d7%a9%d7%95%d7%9d-%d7%93%d7%95%d7%9e%d7%99%d7%a0%d7%95%d7%a1/', 170, 530, 1),
  ('690', 'פיצה בקרנה דומינוס (100 גרם)', 'דומינוס', 'דומינוס', 266, 15, 32, 9, 1, 'גרם', 'ל-100 גרם', 'מאושר', 'לפי Fuder, ל-100 גרם (100 גרם): 266 קלוריות, 15 גרם חלבון, 32 גרם פחמימות, 9 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a4%d7%99%d7%a6%d7%94-%d7%91%d7%a7%d7%a8%d7%a0%d7%94-%d7%93%d7%95%d7%9e%d7%99%d7%a0%d7%95%d7%a1/', null, 266, 1),
  ('691', 'פיצה גריק מיקס דומינוס (100 גרם)', 'דומינוס', 'דומינוס', 336, 13, 44, 12, 1, 'גרם', 'ל-100 גרם', 'מאושר', 'לפי Fuder, ל-100 גרם (100 גרם): 336 קלוריות, 13 גרם חלבון, 44 גרם פחמימות, 12 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a4%d7%99%d7%a6%d7%94-%d7%92%d7%a8%d7%99%d7%a7-%d7%9e%d7%99%d7%a7%d7%a1-%d7%93%d7%95%d7%9e%d7%99%d7%a0%d7%95%d7%a1/', null, 336, 1),
  ('692', 'פיצה ווג''י מיקס דומינוס (100 גרם)', 'דומינוס', 'דומינוס', 267, 11, 33, 8, 1, 'גרם', 'ל-100 גרם', 'מאושר', 'לפי Fuder, ל-100 גרם (100 גרם): 267 קלוריות, 11 גרם חלבון, 33 גרם פחמימות, 8 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a4%d7%99%d7%a6%d7%94-%d7%95%d7%95%d7%92%d7%99-%d7%9e%d7%99%d7%a7%d7%a1-%d7%93%d7%95%d7%9e%d7%99%d7%a0%d7%95%d7%a1/', null, 267, 1),
  ('693', 'פיצה טבעונית (ללא תוספות) דומינוס (100 גרם)', 'דומינוס', 'דומינוס', 243, 5, 43, 6, 1, 'גרם', 'ל-100 גרם', 'מאושר', 'לפי Fuder, ל-100 גרם (100 גרם): 243 קלוריות, 5 גרם חלבון, 43 גרם פחמימות, 6 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a4%d7%99%d7%a6%d7%94-%d7%98%d7%91%d7%a2%d7%95%d7%a0%d7%99%d7%aa-%d7%93%d7%95%d7%9e%d7%99%d7%a0%d7%95%d7%a1/', null, 243, 1),
  ('694', 'פיצה יא סלמי דומינוס (100 גרם)', 'דומינוס', 'דומינוס', 283, 14, 30, 12, 1, 'גרם', 'ל-100 גרם', 'מאושר', 'לפי Fuder, ל-100 גרם (100 גרם): 283 קלוריות, 14 גרם חלבון, 30 גרם פחמימות, 12 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a4%d7%99%d7%a6%d7%94-%d7%99%d7%90-%d7%a1%d7%9c%d7%9e%d7%99-%d7%93%d7%95%d7%9e%d7%99%d7%a0%d7%95%d7%a1/', null, 283, 1),
  ('695', 'פיצה ללא גלוטן (ללא תוספות) דומינוס (100 גרם)', 'דומינוס', 'דומינוס', 332, 8, 40, 16, 1, 'גרם', 'ל-100 גרם', 'מאושר', 'לפי Fuder, ל-100 גרם (100 גרם): 332 קלוריות, 8 גרם חלבון, 40 גרם פחמימות, 16 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a4%d7%99%d7%a6%d7%94-%d7%9c%d7%9c%d7%90-%d7%92%d7%9c%d7%95%d7%98%d7%9f-%d7%93%d7%95%d7%9e%d7%99%d7%a0%d7%95%d7%a1/', null, 332, 1),
  ('696', 'פיצה ללא קשה (ללא תוספות) דומינוס (100 גרם)', 'דומינוס', 'דומינוס', 299, 13, 37, 11, 1, 'גרם', 'ל-100 גרם', 'מאושר', 'לפי Fuder, ל-100 גרם (100 גרם): 299 קלוריות, 13 גרם חלבון, 37 גרם פחמימות, 11 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a4%d7%99%d7%a6%d7%94-%d7%9c%d7%9c%d7%90-%d7%a7%d7%a9%d7%94-%d7%93%d7%95%d7%9e%d7%99%d7%a0%d7%95%d7%a1/', null, 299, 1),
  ('697', 'פיצה מבצק כוסמין (ללא תוספות) דומינוס (100 גרם)', 'דומינוס', 'דומינוס', 224, 10, 31, 6, 1, 'גרם', 'ל-100 גרם', 'מאושר', 'לפי Fuder, ל-100 גרם (100 גרם): 224 קלוריות, 10 גרם חלבון, 31 גרם פחמימות, 6 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a4%d7%99%d7%a6%d7%94-%d7%9e%d7%91%d7%a6%d7%a7-%d7%9b%d7%95%d7%a1%d7%9e%d7%99%d7%9f-%d7%93%d7%95%d7%9e%d7%99%d7%a0%d7%95%d7%a1/', null, 224, 1),
  ('698', 'פיצה צ''יזי קראסט זיתים דומינוס (100 גרם)', 'דומינוס', 'דומינוס', 324, 15, 34, 15, 1, 'גרם', 'ל-100 גרם', 'מאושר', 'לפי Fuder, ל-100 גרם (100 גרם): 324 קלוריות, 15 גרם חלבון, 34 גרם פחמימות, 14.5 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a4%d7%99%d7%a6%d7%94-%d7%a6%d7%99%d7%96%d7%99-%d7%a7%d7%a8%d7%90%d7%a1%d7%98-%d7%96%d7%99%d7%aa%d7%99%d7%9d-%d7%93%d7%95%d7%9e%d7%99%d7%a0%d7%95%d7%a1/', null, 324, 1),
  ('699', 'פיצה צ''יזי קראסט חריפה דומינוס (100 גרם)', 'דומינוס', 'דומינוס', 300, 15, 36, 12, 1, 'גרם', 'ל-100 גרם', 'מאושר', 'לפי Fuder, ל-100 גרם (100 גרם): 300 קלוריות, 15 גרם חלבון, 36 גרם פחמימות, 11.5 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a4%d7%99%d7%a6%d7%94-%d7%a6%d7%99%d7%96%d7%99-%d7%a7%d7%a8%d7%90%d7%a1%d7%98-%d7%97%d7%a8%d7%99%d7%a4%d7%94-%d7%93%d7%95%d7%9e%d7%99%d7%a0%d7%95%d7%a1/', null, 300, 1),
  ('700', 'פיצה צ''יזי קראסט מוצרלה דומינוס (100 גרם)', 'דומינוס', 'דומינוס', 296, 12, 34, 12, 1, 'גרם', 'ל-100 גרם', 'מאושר', 'לפי Fuder, ל-100 גרם (100 גרם): 296 קלוריות, 12 גרם חלבון, 34 גרם פחמימות, 11.6 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a4%d7%99%d7%a6%d7%94-%d7%a6%d7%99%d7%96%d7%99-%d7%a7%d7%a8%d7%90%d7%a1%d7%98-%d7%9e%d7%95%d7%a6%d7%a8%d7%9c%d7%94-%d7%93%d7%95%d7%9e%d7%99%d7%a0%d7%95%d7%a1/', null, 296, 1),
  ('701', 'פיצה צ''יזי קראסט פסטו דומינוס (100 גרם)', 'דומינוס', 'דומינוס', 313, 15, 34, 13, 1, 'גרם', 'ל-100 גרם', 'מאושר', 'לפי Fuder, ל-100 גרם (100 גרם): 313 קלוריות, 15 גרם חלבון, 34 גרם פחמימות, 13 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a4%d7%99%d7%a6%d7%94-%d7%a6%d7%99%d7%96%d7%99-%d7%a7%d7%a8%d7%90%d7%a1%d7%98-%d7%a4%d7%a1%d7%98%d7%95-%d7%93%d7%95%d7%9e%d7%99%d7%a0%d7%95%d7%a1/', null, 313, 1),
  ('702', 'פיצה צ׳יזי מיקס דומינוס (100 גרם)', 'דומינוס', 'דומינוס', 368, 17, 44, 15, 1, 'גרם', 'ל-100 גרם', 'מאושר', 'לפי Fuder, ל-100 גרם (100 גרם): 368 קלוריות, 17 גרם חלבון, 44 גרם פחמימות, 15 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a4%d7%99%d7%a6%d7%94-%d7%a6%d7%b3%d7%99%d7%96%d7%99-%d7%9e%d7%99%d7%a7%d7%a1-%d7%93%d7%95%d7%9e%d7%99%d7%a0%d7%95%d7%a1/', null, 368, 1),
  ('703', 'פיצה קלאסית משפחתית (ללא תוספות) דומינוס (100 גרם)', 'דומינוס', 'דומינוס', 248, 10, 37, 6, 1, 'גרם', 'ל-100 גרם', 'מאושר', 'לפי Fuder, ל-100 גרם (100 גרם): 248 קלוריות, 10 גרם חלבון, 37 גרם פחמימות, 6 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a4%d7%99%d7%a6%d7%94-%d7%a7%d7%9c%d7%90%d7%a1%d7%99%d7%aa-%d7%9e%d7%a9%d7%a4%d7%97%d7%aa%d7%99%d7%aa-%d7%93%d7%95%d7%9e%d7%99%d7%a0%d7%95%d7%a1/', null, 248, 1),
  ('704', 'פיצה קרניבור מיקס דומינוס (100 גרם)', 'דומינוס', 'דומינוס', 357, 17, 40, 14, 1, 'גרם', 'ל-100 גרם', 'מאושר', 'לפי Fuder, ל-100 גרם (100 גרם): 357 קלוריות, 17 גרם חלבון, 40 גרם פחמימות, 14 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a4%d7%99%d7%a6%d7%94-%d7%a7%d7%a8%d7%a0%d7%99%d7%91%d7%95%d7%a8-%d7%9e%d7%99%d7%a7%d7%a1-%d7%93%d7%95%d7%9e%d7%99%d7%a0%d7%95%d7%a1/', null, 357, 1),
  ('705', 'פיצה 4 מחבתות דומינוס (100 גרם)', 'דומינוס', 'דומינוס', 208, 10, 25, 7, 1, 'גרם', 'ל-100 גרם', 'מאושר', 'לפי Fuder, ל-100 גרם (100 גרם): 208 קלוריות, 10 גרם חלבון, 25 גרם פחמימות, 7 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a4%d7%99%d7%a6%d7%94-4-%d7%9e%d7%97%d7%91%d7%aa%d7%95%d7%aa-%d7%93%d7%95%d7%9e%d7%99%d7%a0%d7%95%d7%a1/', null, 208, 1),
  ('706', 'פיצה PRO כוסמין דומינוס (100 גרם)', 'דומינוס', 'דומינוס', 309, 17, 32, 11, 1, 'גרם', 'ל-100 גרם', 'מאושר', 'לפי Fuder, ל-100 גרם (100 גרם): 309 קלוריות, 17 גרם חלבון, 32 גרם פחמימות, 11 גרם שומן.', 'https://www.fuder.co.il/meals_rest/%d7%a4%d7%99%d7%a6%d7%94-pro-%d7%9b%d7%95%d7%a1%d7%9e%d7%99%d7%9f-%d7%93%d7%95%d7%9e%d7%99%d7%a0%d7%95%d7%a1/', null, 309, 1)
on conflict (id) do update set
  name = excluded.name,
  brand = excluded.brand,
  category = excluded.category,
  calories = excluded.calories,
  protein = excluded.protein,
  carbs = excluded.carbs,
  fat = excluded.fat,
  package_quantity = excluded.package_quantity,
  package_unit = excluded.package_unit,
  serving_label = excluded.serving_label,
  verification_status = excluded.verification_status,
  notes = excluded.notes,
  source_url = excluded.source_url,
  unit_weight_grams = excluded.unit_weight_grams,
  calories_per_unit = excluded.calories_per_unit,
  units_per_package = excluded.units_per_package,
  updated_at = now();

do $$
begin
  if (select count(*) from public.foods where category = 'דומינוס') <> 18 then
    raise exception 'fuder_restaurant_upsert_failed';
  end if;
end $$;

commit;
